# GridSeachCV()

In [11]:
import pandas as pd
from sklearn.model_selection import KFold , StratifiedKFold, GridSearchCV
from sklearn.ensemble import GradientBoostingClassifier


import warnings
warnings.filterwarnings('ignore')

In [12]:
df = pd.read_csv(r"C:\Users\PGCP-AI.STUDENTSDC\Desktop\Machine_Learning\Cases\Vehicle Silhouettes\Vehicle.csv")
df.sample(5)

,Comp,Circ,D.Circ,Rad.Ra,Pr.Axis.Ra,Max.L.Ra,Scat.Ra,Elong,Pr.Axis.Rect,Max.L.Rect,Sc.Var.Maxis,Sc.Var.maxis,Ra.Gyr,Skew.Maxis,Skew.maxis,Kurt.maxis,Kurt.Maxis,Holl.Ra,Class
333,86,42,65,125,54,7,150,45,19,140,171,327,172,85,2,8,180,182,bus
397,89,41,75,162,66,5,153,43,19,136,175,352,154,72,2,0,188,195,bus
755,86,39,58,125,55,5,117,57,17,134,140,204,148,69,7,6,190,194,van
694,100,43,92,197,62,10,180,36,21,143,200,489,153,64,6,9,195,205,saab
232,81,44,68,120,53,6,151,45,19,147,170,333,178,86,4,5,179,183,bus

In [13]:
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
import numpy as np

X , y = df.drop('Class',axis=1) , df['Class']
encoder = LabelEncoder()
y_en = encoder.fit_transform(y)
kfold = StratifiedKFold(n_splits=5 , shuffle=True , random_state=26)
lr = LogisticRegression()

In [15]:
params = {
    'solver':['lbfgs', 'saga', 'sag', 'newton-cg', 'newton-cholesky'],
    'C' : np.linspace(0.01,3,5)
}
gcv = GridSearchCV(lr,param_grid=params,cv=kfold, scoring='neg_log_loss')
gcv.fit(X,y_en)

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=26, shuffle=True),
             estimator=LogisticRegression(),
             param_grid={'C': array([0.01  , 0.7575, 1.505 , 2.2525, 3.    ]),
                         'solver': ['lbfgs', 'saga', 'sag', 'newton-cg',
                                    'newton-cholesky']},
             scoring='neg_log_loss')

In [16]:
print('Best Params ->',gcv.best_params_)
print('Best Score ->',gcv.best_score_)

Best Params -> {'C': np.float64(0.7575000000000001), 'solver': 'newton-cg'}
Best Score -> -0.41460687009627517

# Exercise

In [18]:
df = pd.read_csv(r"C:\Users\PGCP-AI.STUDENTSDC\Desktop\Machine_Learning\Cases\Concrete_Strength\Concrete_Data.csv")
df.sample(5)

,Cement,Blast,Fly,Water,Superplasticizer,Coarse,Fine,Age,Strength
483,446.0,24.0,79.0,162.0,11.6,967.0,712.0,56,55.25
296,168.9,42.2,124.3,158.3,10.8,1080.8,796.2,28,31.12
898,336.0,0.0,0.0,182.0,3.0,986.0,817.0,28,44.86
99,469.0,117.2,0.0,137.8,32.2,852.1,840.5,7,54.90
721,310.0,0.0,0.0,192.0,0.0,1012.0,830.0,3,11.85

In [20]:
from sklearn.model_selection import train_test_split
X , y = df.drop('Strength',axis=1) , df['Strength']
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=26)

In [21]:
from sklearn.ensemble import GradientBoostingRegressor
from xgboost import XGBRegressor
from sklearn.model_selection import RandomizedSearchCV
params = {
    'max_depth':[None,2,3,4],
    'learning_rate' : np.linspace(0.01,0.9,10),
    'n_estimators':[25,50,100]
}

kfold = KFold(n_splits=5, shuffle=True, random_state=26)
gbm = XGBRegressor(random_state=26)
gcv = GridSearchCV(gbm, param_grid=params,cv=kfold,scoring='r2')
gcv.fit(X,y)

GridSearchCV(cv=KFold(n_splits=5, random_state=26, shuffle=True),
             estimator=XGBRegressor(base_score=None, booster=None,
                                    callbacks=None, colsample_bylevel=None,
                                    colsample_bynode=None,
                                    colsample_bytree=None, device=None,
                                    early_stopping_rounds=None,
                                    enable_categorical=True, eval_metric=None,
                                    feature_types=None, feature_weights=None,
                                    gamma=None, grow_policy=None,
                                    impor...
                                    max_depth=None, max_leaves=None,
                                    min_child_weight=None, missing=nan,
                                    monotone_constraints=None,
                                    multi_strategy=None, n_estimators=None,
                                    n_jobs=None, num_parallel_tree=None, ...),
             param_grid={'learning_rate': array([0.01      , 0.10888889, 0.20777778, 0.30666667, 0.40555556,
       0.50444444, 0.60333333, 0.70222222, 0.80111111, 0.9       ]),
                         'max_depth': [None, 2, 3, 4],
                         'n_estimators': [25, 50, 100]},
             scoring='r2')

In [22]:
print('Best Params ->',gcv.best_params_)
print('Best Score ->',gcv.best_score_)

Best Params -> {'learning_rate': np.float64(0.6033333333333333), 'max_depth': 3, 'n_estimators': 100}
Best Score -> 0.935401012517735

### Test On Unlabeled Data

In [23]:
test_df = pd.read_csv(r"C:\Users\PGCP-AI.STUDENTSDC\Desktop\Machine_Learning\Cases\Concrete_Strength\testConcrete.csv")
test_df.sample(5)

    Cement  Blast  Fly  Water  Superplasticizer  Coarse  Fine  Age
9      206     38    0    103                 2     818   719  191
10     247     64   26    175                 2     822   898  183
13     125     93    0    200                 5     893   671  113
7      393     49   82    132                 1     887   830  271
11     223    102    0    110                 2     808   854  270

In [24]:
pred_df = gcv.predict(test_df)
pred_df

array([68.533485, 44.278156, 43.30317 , 36.11119 , 50.87477 , 13.594891,
       46.644585, 65.02611 , 53.04127 , 56.998302, 53.745834, 47.816093,
       45.142815, 43.668945], dtype=float32)

In [25]:
# Using best hyperparameter
best_model = XGBRegressor(**gcv.best_params_, random_state=26)
best_model.fit(X,y)
best_model.predict(test_df)

array([68.533485, 44.278156, 43.30317 , 36.11119 , 50.87477 , 13.594891,
       46.644585, 65.02611 , 53.04127 , 56.998302, 53.745834, 47.816093,
       45.142815, 43.668945], dtype=float32)

In [26]:
bm = gcv.best_estimator_
bm.predict(test_df)

array([68.533485, 44.278156, 43.30317 , 36.11119 , 50.87477 , 13.594891,
       46.644585, 65.02611 , 53.04127 , 56.998302, 53.745834, 47.816093,
       45.142815, 43.668945], dtype=float32)

# Exercise With Pipeline

In [27]:
df = pd.read_csv(r"C:\Users\PGCP-AI.STUDENTSDC\Desktop\Machine_Learning\Cases\Medical_Cost_Personal\insurance.csv")
df.sample(5)

      age     sex    bmi  children smoker     region      charges
1195   19  female  27.93         3     no  northwest  18838.70366
365    49  female  30.78         1     no  northeast   9778.34720
1315   18    male  28.31         1     no  northeast  11272.33139
468    28  female  24.32         1     no  northeast  23288.92840
1221   40    male  24.97         2     no  southeast   6593.50830

In [28]:
X , y = df.drop('charges',axis=1) , df['charges']

In [29]:
from sklearn.compose import make_column_transformer, make_column_selector
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline

encoder = OneHotEncoder(sparse_output=False, drop='first')
ct = make_column_transformer((encoder,make_column_selector(dtype_include='object')),
                             ('passthrough',make_column_selector(dtype_include='number')),
                             verbose_feature_names_out=False)

gbm = XGBRegressor(random_state=26)
pipe = Pipeline([('OHE',ct),('GBM',gbm)])
# pipe.get_params()

In [30]:
params = {
    'GBM__learning_rate' : np.linspace(0.01,0.9,10),
    'GBM__max_depth':[None,2,3,4],
    'GBM__n_estimators':[25,50,100]
}

kfold = KFold(n_splits=5, shuffle=True, random_state=26)
gcv = GridSearchCV(pipe, param_grid=params,cv=kfold,scoring='r2')
gcv.fit(X,y)

GridSearchCV(cv=KFold(n_splits=5, random_state=26, shuffle=True),
             estimator=Pipeline(steps=[('OHE',
                                        ColumnTransformer(transformers=[('onehotencoder',
                                                                         OneHotEncoder(drop='first',
                                                                                       sparse_output=False),
                                                                         <sklearn.compose._column_transformer.make_column_selector object at 0x0000016C688E5FD0>),
                                                                        ('passthrough',
                                                                         'passthrough',
                                                                         <sklearn.compose._column_transformer.make_...
                                                     min_child_weight=None,
                                                     missing=nan,
                                                     monotone_constraints=None,
                                                     multi_strategy=None,
                                                     n_estimators=None,
                                                     n_jobs=None,
                                                     num_parallel_tree=None, ...))]),
             param_grid={'GBM__learning_rate': array([0.01      , 0.10888889, 0.20777778, 0.30666667, 0.40555556,
       0.50444444, 0.60333333, 0.70222222, 0.80111111, 0.9       ]),
                         'GBM__max_depth': [None, 2, 3, 4],
                         'GBM__n_estimators': [25, 50, 100]},
             scoring='r2')

In [31]:
print('Best Params ->',gcv.best_params_)
print('Best Score ->',gcv.best_score_)

Best Params -> {'GBM__learning_rate': np.float64(0.10888888888888888), 'GBM__max_depth': 3, 'GBM__n_estimators': 50}
Best Score -> 0.8632949136193883

# Verbose 
To get details of gridsearch default(verbose=False/0)

In [32]:
gcv = GridSearchCV(pipe, param_grid=params,cv=kfold,scoring='r2',verbose=1)
gcv.fit(X,y)

Fitting 5 folds for each of 120 candidates, totalling 600 fits

GridSearchCV(cv=KFold(n_splits=5, random_state=26, shuffle=True),
             estimator=Pipeline(steps=[('OHE',
                                        ColumnTransformer(transformers=[('onehotencoder',
                                                                         OneHotEncoder(drop='first',
                                                                                       sparse_output=False),
                                                                         <sklearn.compose._column_transformer.make_column_selector object at 0x0000016C688E5FD0>),
                                                                        ('passthrough',
                                                                         'passthrough',
                                                                         <sklearn.compose._column_transformer.make_...
                                                     min_child_weight=None,
                                                     missing=nan,
                                                     monotone_constraints=None,
                                                     multi_strategy=None,
                                                     n_estimators=None,
                                                     n_jobs=None,
                                                     num_parallel_tree=None, ...))]),
             param_grid={'GBM__learning_rate': array([0.01      , 0.10888889, 0.20777778, 0.30666667, 0.40555556,
       0.50444444, 0.60333333, 0.70222222, 0.80111111, 0.9       ]),
                         'GBM__max_depth': [None, 2, 3, 4],
                         'GBM__n_estimators': [25, 50, 100]},
             scoring='r2', verbose=1)

In [33]:
gcv = GridSearchCV(pipe, param_grid=params,cv=kfold,scoring='r2',verbose=2)
gcv.fit(X,y)

Fitting 5 folds for each of 120 candidates, totalling 600 fits
[CV] END GBM__learning_rate=0.01, GBM__max_depth=None, GBM__n_estimators=25; total time=   0.0s
[CV] END GBM__learning_rate=0.01, GBM__max_depth=None, GBM__n_estimators=25; total time=   0.0s
[CV] END GBM__learning_rate=0.01, GBM__max_depth=None, GBM__n_estimators=25; total time=   0.0s
[CV] END GBM__learning_rate=0.01, GBM__max_depth=None, GBM__n_estimators=25; total time=   0.0s
[CV] END GBM__learning_rate=0.01, GBM__max_depth=None, GBM__n_estimators=25; total time=   0.0s
[CV] END GBM__learning_rate=0.01, GBM__max_depth=None, GBM__n_estimators=50; total time=   0.1s
[CV] END GBM__learning_rate=0.01, GBM__max_depth=None, GBM__n_estimators=50; total time=   0.1s
[CV] END GBM__learning_rate=0.01, GBM__max_depth=None, GBM__n_estimators=50; total time=   0.1s
[CV] END GBM__learning_rate=0.01, GBM__max_depth=None, GBM__n_estimators=50; total time=   0.1s
[CV] END GBM__learning_rate=0.01, GBM__max_depth=None, GBM__n_estimators=50; total time=   0.1s
[CV] END GBM__learning_rate=0.01, GBM__max_depth=None, GBM__n_estimators=100; total time=   0.2s
[CV] END GBM__learning_rate=0.01, GBM__max_depth=None, GBM__n_estimators=100; total time=   0.2s
[CV] END GBM__learning_rate=0.01, GBM__max_depth=None, GBM__n_estimators=100; total time=   0.1s
[CV] END GBM__learning_rate=0.01, GBM__max_depth=None, GBM__n_estimators=100; total time=   0.2s
[CV] END GBM__learning_rate=0.01, GBM__max_depth=None, GBM__n_estimators=100; total time=   0.1s
[CV] END GBM__learning_rate=0.01, GBM__max_depth=2, GBM__n_estimators=25; total time=   0.0s
[CV] END GBM__learning_rate=0.01, GBM__max_depth=2, GBM__n_estimators=25; total time=   0.0s
[CV] END GBM__learning_rate=0.01, GBM__max_depth=2, GBM__n_estimators=25; total time=   0.0s
[CV] END GBM__learning_rate=0.01, GBM__max_depth=2, GBM__n_estimators=25; total time=   0.0s
[CV] END GBM__learning_rate=0.01, GBM__max_depth=2, GBM__n_estimators=25; total time=   0.0s
[CV] END GBM__learning_rate=0.01, GBM__max_depth=2, GBM__n_estimators=50; total time=   0.0s
[CV] END GBM__learning_rate=0.01, GBM__max_depth=2, GBM__n_estimators=50; total time=   0.0s
[CV] END GBM__learning_rate=0.01, GBM__max_depth=2, GBM__n_estimators=50; total time=   0.0s
[CV] END GBM__learning_rate=0.01, GBM__max_depth=2, GBM__n_estimators=50; total time=   0.0s
[CV] END GBM__learning_rate=0.01, GBM__max_depth=2, GBM__n_estimators=50; total time=   0.0s
[CV] END GBM__learning_rate=0.01, GBM__max_depth=2, GBM__n_estimators=100; total time=   0.1s
[CV] END GBM__learning_rate=0.01, GBM__max_depth=2, GBM__n_estimators=100; total time=   0.1s
[CV] END GBM__learning_rate=0.01, GBM__max_depth=2, GBM__n_estimators=100; total time=   0.1s
[CV] END GBM__learning_rate=0.01, GBM__max_depth=2, GBM__n_estimators=100; total time=   0.1s
[CV] END GBM__learning_rate=0.01, GBM__max_depth=2, GBM__n_estimators=100; total time=   0.1s
[CV] END GBM__learning_rate=0.01, GBM__max_depth=3, GBM__n_estimators=25; total time=   0.0s
[CV] END GBM__learning_rate=0.01, GBM__max_depth=3, GBM__n_estimators=25; total time=   0.0s
[CV] END GBM__learning_rate=0.01, GBM__max_depth=3, GBM__n_estimators=25; total time=   0.0s
[CV] END GBM__learning_rate=0.01, GBM__max_depth=3, GBM__n_estimators=25; total time=   0.0s
[CV] END GBM__learning_rate=0.01, GBM__max_depth=3, GBM__n_estimators=25; total time=   0.0s
[CV] END GBM__learning_rate=0.01, GBM__max_depth=3, GBM__n_estimators=50; total time=   0.0s
[CV] END GBM__learning_rate=0.01, GBM__max_depth=3, GBM__n_estimators=50; total time=   0.0s
[CV] END GBM__learning_rate=0.01, GBM__max_depth=3, GBM__n_estimators=50; total time=   0.0s
[CV] END GBM__learning_rate=0.01, GBM__max_depth=3, GBM__n_estimators=50; total time=   0.0s
[CV] END GBM__learning_rate=0.01, GBM__max_depth=3, GBM__n_estimators=50; total time=   0.0s
[CV] END GBM__learning_rate=0.01, GBM__max_depth=3, GBM__n_estimators=100; total time=   0.1s
[CV] END GBM__learning_rate=0.01, GBM__max_depth=3, GBM__n_estimators=100; total time=   0.1s
[CV] END GBM__learning_rate=0.01, GBM__max_depth=3, GBM__n_estimators=100; total time=   0.1s
[CV] END GBM__learning_rate=0.01, GBM__max_depth=3, GBM__n_estimators=100; total time=   0.1s
[CV] END GBM__learning_rate=0.01, GBM__max_depth=3, GBM__n_estimators=100; total time=   0.1s
[CV] END GBM__learning_rate=0.01, GBM__max_depth=4, GBM__n_estimators=25; total time=   0.0s
[CV] END GBM__learning_rate=0.01, GBM__max_depth=4, GBM__n_estimators=25; total time=   0.0s
[CV] END GBM__learning_rate=0.01, GBM__max_depth=4, GBM__n_estimators=25; total time=   0.0s
[CV] END GBM__learning_rate=0.01, GBM__max_depth=4, GBM__n_estimators=25; total time=   0.0s
[CV] END GBM__learning_rate=0.01, GBM__max_depth=4, GBM__n_estimators=25; total time=   0.0s
[CV] END GBM__learning_rate=0.01, GBM__max_depth=4, GBM__n_estimators=50; total time=   0.0s
[CV] END GBM__learning_rate=0.01, GBM__max_depth=4, GBM__n_estimators=50; total time=   0.0s
[CV] END GBM__learning_rate=0.01, GBM__max_depth=4, GBM__n_estimators=50; total time=   0.0s
[CV] END GBM__learning_rate=0.01, GBM__max_depth=4, GBM__n_estimators=50; total time=   0.0s
[CV] END GBM__learning_rate=0.01, GBM__max_depth=4, GBM__n_estimators=50; total time=   0.0s
[CV] END GBM__learning_rate=0.01, GBM__max_depth=4, GBM__n_estimators=100; total time=   0.1s
[CV] END GBM__learning_rate=0.01, GBM__max_depth=4, GBM__n_estimators=100; total time=   0.1s
[CV] END GBM__learning_rate=0.01, GBM__max_depth=4, GBM__n_estimators=100; total time=   0.1s
[CV] END GBM__learning_rate=0.01, GBM__max_depth=4, GBM__n_estimators=100; total time=   0.1s
[CV] END GBM__learning_rate=0.01, GBM__max_depth=4, GBM__n_estimators=100; total time=   0.1s
[CV] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=None, GBM__n_estimators=25; total time=   0.0s
[CV] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=None, GBM__n_estimators=25; total time=   0.2s
[CV] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=None, GBM__n_estimators=25; total time=   0.0s
[CV] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=None, GBM__n_estimators=25; total time=   0.0s
[CV] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=None, GBM__n_estimators=25; total time=   0.0s
[CV] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=None, GBM__n_estimators=50; total time=   0.0s
[CV] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=None, GBM__n_estimators=50; total time=   0.1s
[CV] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=None, GBM__n_estimators=50; total time=   0.1s
[CV] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=None, GBM__n_estimators=50; total time=   0.0s
[CV] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=None, GBM__n_estimators=50; total time=   0.0s
[CV] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=None, GBM__n_estimators=100; total time=   0.2s
[CV] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=None, GBM__n_estimators=100; total time=   0.2s
[CV] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=None, GBM__n_estimators=100; total time=   0.3s
[CV] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=None, GBM__n_estimators=100; total time=   0.2s
[CV] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=None, GBM__n_estimators=100; total time=   0.2s
[CV] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=2, GBM__n_estimators=25; total time=   0.0s
[CV] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=2, GBM__n_estimators=25; total time=   0.0s
[CV] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=2, GBM__n_estimators=25; total time=   0.0s
[CV] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=2, GBM__n_estimators=25; total time=   0.0s
[CV] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=2, GBM__n_estimators=25; total time=   0.0s
[CV] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=2, GBM__n_estimators=50; total time=   0.0s
[CV] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=2, GBM__n_estimators=50; total time=   0.0s
[CV] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=2, GBM__n_estimators=50; total time=   0.0s
[CV] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=2, GBM__n_estimators=50; total time=   0.0s
[CV] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=2, GBM__n_estimators=50; total time=   0.0s
[CV] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=2, GBM__n_estimators=100; total time=   0.1s
[CV] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=2, GBM__n_estimators=100; total time=   0.1s
[CV] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=2, GBM__n_estimators=100; total time=   0.1s
[CV] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=2, GBM__n_estimators=100; total time=   0.1s
[CV] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=2, GBM__n_estimators=100; total time=   0.1s
[CV] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=3, GBM__n_estimators=25; total time=   0.0s
[CV] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=3, GBM__n_estimators=25; total time=   0.0s
[CV] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=3, GBM__n_estimators=25; total time=   0.0s
[CV] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=3, GBM__n_estimators=25; total time=   0.0s
[CV] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=3, GBM__n_estimators=25; total time=   0.0s
[CV] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=3, GBM__n_estimators=50; total time=   0.0s
[CV] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=3, GBM__n_estimators=50; total time=   0.0s
[CV] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=3, GBM__n_estimators=50; total time=   0.0s
[CV] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=3, GBM__n_estimators=50; total time=   0.0s
[CV] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=3, GBM__n_estimators=50; total time=   0.0s
[CV] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=3, GBM__n_estimators=100; total time=   0.1s
[CV] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=3, GBM__n_estimators=100; total time=   0.1s
[CV] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=3, GBM__n_estimators=100; total time=   0.1s
[CV] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=3, GBM__n_estimators=100; total time=   0.1s
[CV] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=3, GBM__n_estimators=100; total time=   0.1s
[CV] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=4, GBM__n_estimators=25; total time=   0.0s
[CV] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=4, GBM__n_estimators=25; total time=   0.0s
[CV] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=4, GBM__n_estimators=25; total time=   0.0s
[CV] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=4, GBM__n_estimators=25; total time=   0.0s
[CV] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=4, GBM__n_estimators=25; total time=   0.0s
[CV] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=4, GBM__n_estimators=50; total time=   0.0s
[CV] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=4, GBM__n_estimators=50; total time=   0.0s
[CV] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=4, GBM__n_estimators=50; total time=   0.0s
[CV] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=4, GBM__n_estimators=50; total time=   0.0s
[CV] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=4, GBM__n_estimators=50; total time=   0.0s
[CV] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=4, GBM__n_estimators=100; total time=   0.1s
[CV] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=4, GBM__n_estimators=100; total time=   0.1s
[CV] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=4, GBM__n_estimators=100; total time=   0.1s
[CV] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=4, GBM__n_estimators=100; total time=   0.1s
[CV] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=4, GBM__n_estimators=100; total time=   0.1s
[CV] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=None, GBM__n_estimators=25; total time=   0.0s
[CV] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=None, GBM__n_estimators=25; total time=   0.0s
[CV] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=None, GBM__n_estimators=25; total time=   0.0s
[CV] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=None, GBM__n_estimators=25; total time=   0.0s
[CV] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=None, GBM__n_estimators=25; total time=   0.0s
[CV] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=None, GBM__n_estimators=50; total time=   0.1s
[CV] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=None, GBM__n_estimators=50; total time=   0.0s
[CV] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=None, GBM__n_estimators=50; total time=   0.0s
[CV] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=None, GBM__n_estimators=50; total time=   0.0s
[CV] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=None, GBM__n_estimators=50; total time=   0.0s
[CV] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=None, GBM__n_estimators=100; total time=   0.2s
[CV] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=None, GBM__n_estimators=100; total time=   0.2s
[CV] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=None, GBM__n_estimators=100; total time=   0.2s
[CV] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=None, GBM__n_estimators=100; total time=   0.2s
[CV] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=None, GBM__n_estimators=100; total time=   0.2s
[CV] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=2, GBM__n_estimators=25; total time=   0.0s
[CV] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=2, GBM__n_estimators=25; total time=   0.0s
[CV] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=2, GBM__n_estimators=25; total time=   0.0s
[CV] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=2, GBM__n_estimators=25; total time=   0.0s
[CV] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=2, GBM__n_estimators=25; total time=   0.0s
[CV] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=2, GBM__n_estimators=50; total time=   0.0s
[CV] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=2, GBM__n_estimators=50; total time=   0.0s
[CV] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=2, GBM__n_estimators=50; total time=   0.0s
[CV] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=2, GBM__n_estimators=50; total time=   0.0s
[CV] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=2, GBM__n_estimators=50; total time=   0.0s
[CV] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=2, GBM__n_estimators=100; total time=   0.1s
[CV] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=2, GBM__n_estimators=100; total time=   0.1s
[CV] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=2, GBM__n_estimators=100; total time=   0.1s
[CV] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=2, GBM__n_estimators=100; total time=   0.1s
[CV] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=2, GBM__n_estimators=100; total time=   0.1s
[CV] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=3, GBM__n_estimators=25; total time=   0.0s
[CV] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=3, GBM__n_estimators=25; total time=   0.0s
[CV] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=3, GBM__n_estimators=25; total time=   0.0s
[CV] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=3, GBM__n_estimators=25; total time=   0.0s
[CV] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=3, GBM__n_estimators=25; total time=   0.0s
[CV] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=3, GBM__n_estimators=50; total time=   0.0s
[CV] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=3, GBM__n_estimators=50; total time=   0.0s
[CV] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=3, GBM__n_estimators=50; total time=   0.0s
[CV] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=3, GBM__n_estimators=50; total time=   0.0s
[CV] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=3, GBM__n_estimators=50; total time=   0.0s
[CV] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=3, GBM__n_estimators=100; total time=   0.1s
[CV] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=3, GBM__n_estimators=100; total time=   0.1s
[CV] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=3, GBM__n_estimators=100; total time=   0.1s
[CV] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=3, GBM__n_estimators=100; total time=   0.1s
[CV] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=3, GBM__n_estimators=100; total time=   0.1s
[CV] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=4, GBM__n_estimators=25; total time=   0.0s
[CV] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=4, GBM__n_estimators=25; total time=   0.0s
[CV] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=4, GBM__n_estimators=25; total time=   0.0s
[CV] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=4, GBM__n_estimators=25; total time=   0.0s
[CV] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=4, GBM__n_estimators=25; total time=   0.0s
[CV] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=4, GBM__n_estimators=50; total time=   0.0s
[CV] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=4, GBM__n_estimators=50; total time=   0.0s
[CV] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=4, GBM__n_estimators=50; total time=   0.0s
[CV] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=4, GBM__n_estimators=50; total time=   0.0s
[CV] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=4, GBM__n_estimators=50; total time=   0.0s
[CV] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=4, GBM__n_estimators=100; total time=   0.1s
[CV] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=4, GBM__n_estimators=100; total time=   0.1s
[CV] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=4, GBM__n_estimators=100; total time=   0.1s
[CV] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=4, GBM__n_estimators=100; total time=   0.1s
[CV] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=4, GBM__n_estimators=100; total time=   0.1s
[CV] END GBM__learning_rate=0.30666666666666664, GBM__max_depth=None, GBM__n_estimators=25; total time=   0.0s
[CV] END GBM__learning_rate=0.30666666666666664, GBM__max_depth=None, GBM__n_estimators=25; total time=   0.0s
[CV] END GBM__learning_rate=0.30666666666666664, GBM__max_depth=None, GBM__n_estimators=25; total time=   0.0s
[CV] END GBM__learning_rate=0.30666666666666664, GBM__max_depth=None, GBM__n_estimators=25; total time=   0.0s
[CV] END GBM__learning_rate=0.30666666666666664, GBM__max_depth=None, GBM__n_estimators=25; total time=   0.0s
[CV] END GBM__learning_rate=0.30666666666666664, GBM__max_depth=None, GBM__n_estimators=50; total time=   0.1s
[CV] END GBM__learning_rate=0.30666666666666664, GBM__max_depth=None, GBM__n_estimators=50; total time=   0.1s
[CV] END GBM__learning_rate=0.30666666666666664, GBM__max_depth=None, GBM__n_estimators=50; total time=   0.1s
[CV] END GBM__learning_rate=0.30666666666666664, GBM__max_depth=None, GBM__n_estimators=50; total time=   0.1s
[CV] END GBM__learning_rate=0.30666666666666664, GBM__max_depth=None, GBM__n_estimators=50; total time=   0.1s

GridSearchCV(cv=KFold(n_splits=5, random_state=26, shuffle=True),
             estimator=Pipeline(steps=[('OHE',
                                        ColumnTransformer(transformers=[('onehotencoder',
                                                                         OneHotEncoder(drop='first',
                                                                                       sparse_output=False),
                                                                         <sklearn.compose._column_transformer.make_column_selector object at 0x0000016C688E5FD0>),
                                                                        ('passthrough',
                                                                         'passthrough',
                                                                         <sklearn.compose._column_transformer.make_...
                                                     min_child_weight=None,
                                                     missing=nan,
                                                     monotone_constraints=None,
                                                     multi_strategy=None,
                                                     n_estimators=None,
                                                     n_jobs=None,
                                                     num_parallel_tree=None, ...))]),
             param_grid={'GBM__learning_rate': array([0.01      , 0.10888889, 0.20777778, 0.30666667, 0.40555556,
       0.50444444, 0.60333333, 0.70222222, 0.80111111, 0.9       ]),
                         'GBM__max_depth': [None, 2, 3, 4],
                         'GBM__n_estimators': [25, 50, 100]},
             scoring='r2', verbose=2)

In [34]:
gcv = GridSearchCV(pipe, param_grid=params,cv=kfold,scoring='r2',verbose=3)
gcv.fit(X,y)

Fitting 5 folds for each of 120 candidates, totalling 600 fits
[CV 1/5] END GBM__learning_rate=0.01, GBM__max_depth=None, GBM__n_estimators=25;, score=0.332 total time=   0.0s
[CV 2/5] END GBM__learning_rate=0.01, GBM__max_depth=None, GBM__n_estimators=25;, score=0.340 total time=   0.0s
[CV 3/5] END GBM__learning_rate=0.01, GBM__max_depth=None, GBM__n_estimators=25;, score=0.312 total time=   0.0s
[CV 4/5] END GBM__learning_rate=0.01, GBM__max_depth=None, GBM__n_estimators=25;, score=0.348 total time=   0.0s
[CV 5/5] END GBM__learning_rate=0.01, GBM__max_depth=None, GBM__n_estimators=25;, score=0.333 total time=   0.0s
[CV 1/5] END GBM__learning_rate=0.01, GBM__max_depth=None, GBM__n_estimators=50;, score=0.534 total time=   0.0s
[CV 2/5] END GBM__learning_rate=0.01, GBM__max_depth=None, GBM__n_estimators=50;, score=0.549 total time=   0.0s
[CV 3/5] END GBM__learning_rate=0.01, GBM__max_depth=None, GBM__n_estimators=50;, score=0.500 total time=   0.1s
[CV 4/5] END GBM__learning_rate=0.01, GBM__max_depth=None, GBM__n_estimators=50;, score=0.562 total time=   0.0s
[CV 5/5] END GBM__learning_rate=0.01, GBM__max_depth=None, GBM__n_estimators=50;, score=0.539 total time=   0.0s
[CV 1/5] END GBM__learning_rate=0.01, GBM__max_depth=None, GBM__n_estimators=100;, score=0.732 total time=   0.2s
[CV 2/5] END GBM__learning_rate=0.01, GBM__max_depth=None, GBM__n_estimators=100;, score=0.751 total time=   0.2s
[CV 3/5] END GBM__learning_rate=0.01, GBM__max_depth=None, GBM__n_estimators=100;, score=0.684 total time=   0.1s
[CV 4/5] END GBM__learning_rate=0.01, GBM__max_depth=None, GBM__n_estimators=100;, score=0.770 total time=   0.2s
[CV 5/5] END GBM__learning_rate=0.01, GBM__max_depth=None, GBM__n_estimators=100;, score=0.749 total time=   0.2s
[CV 1/5] END GBM__learning_rate=0.01, GBM__max_depth=2, GBM__n_estimators=25;, score=0.319 total time=   0.0s
[CV 2/5] END GBM__learning_rate=0.01, GBM__max_depth=2, GBM__n_estimators=25;, score=0.324 total time=   0.0s
[CV 3/5] END GBM__learning_rate=0.01, GBM__max_depth=2, GBM__n_estimators=25;, score=0.302 total time=   0.0s
[CV 4/5] END GBM__learning_rate=0.01, GBM__max_depth=2, GBM__n_estimators=25;, score=0.353 total time=   0.0s
[CV 5/5] END GBM__learning_rate=0.01, GBM__max_depth=2, GBM__n_estimators=25;, score=0.319 total time=   0.0s
[CV 1/5] END GBM__learning_rate=0.01, GBM__max_depth=2, GBM__n_estimators=50;, score=0.512 total time=   0.0s
[CV 2/5] END GBM__learning_rate=0.01, GBM__max_depth=2, GBM__n_estimators=50;, score=0.524 total time=   0.0s
[CV 3/5] END GBM__learning_rate=0.01, GBM__max_depth=2, GBM__n_estimators=50;, score=0.485 total time=   0.0s
[CV 4/5] END GBM__learning_rate=0.01, GBM__max_depth=2, GBM__n_estimators=50;, score=0.564 total time=   0.0s
[CV 5/5] END GBM__learning_rate=0.01, GBM__max_depth=2, GBM__n_estimators=50;, score=0.518 total time=   0.0s
[CV 1/5] END GBM__learning_rate=0.01, GBM__max_depth=2, GBM__n_estimators=100;, score=0.703 total time=   0.1s
[CV 2/5] END GBM__learning_rate=0.01, GBM__max_depth=2, GBM__n_estimators=100;, score=0.723 total time=   0.1s
[CV 3/5] END GBM__learning_rate=0.01, GBM__max_depth=2, GBM__n_estimators=100;, score=0.665 total time=   0.1s
[CV 4/5] END GBM__learning_rate=0.01, GBM__max_depth=2, GBM__n_estimators=100;, score=0.764 total time=   0.1s
[CV 5/5] END GBM__learning_rate=0.01, GBM__max_depth=2, GBM__n_estimators=100;, score=0.721 total time=   0.1s
[CV 1/5] END GBM__learning_rate=0.01, GBM__max_depth=3, GBM__n_estimators=25;, score=0.328 total time=   0.0s
[CV 2/5] END GBM__learning_rate=0.01, GBM__max_depth=3, GBM__n_estimators=25;, score=0.342 total time=   0.0s
[CV 3/5] END GBM__learning_rate=0.01, GBM__max_depth=3, GBM__n_estimators=25;, score=0.310 total time=   0.0s
[CV 4/5] END GBM__learning_rate=0.01, GBM__max_depth=3, GBM__n_estimators=25;, score=0.350 total time=   0.0s
[CV 5/5] END GBM__learning_rate=0.01, GBM__max_depth=3, GBM__n_estimators=25;, score=0.334 total time=   0.0s
[CV 1/5] END GBM__learning_rate=0.01, GBM__max_depth=3, GBM__n_estimators=50;, score=0.529 total time=   0.0s
[CV 2/5] END GBM__learning_rate=0.01, GBM__max_depth=3, GBM__n_estimators=50;, score=0.551 total time=   0.1s
[CV 3/5] END GBM__learning_rate=0.01, GBM__max_depth=3, GBM__n_estimators=50;, score=0.501 total time=   0.0s
[CV 4/5] END GBM__learning_rate=0.01, GBM__max_depth=3, GBM__n_estimators=50;, score=0.563 total time=   0.0s
[CV 5/5] END GBM__learning_rate=0.01, GBM__max_depth=3, GBM__n_estimators=50;, score=0.541 total time=   0.0s
[CV 1/5] END GBM__learning_rate=0.01, GBM__max_depth=3, GBM__n_estimators=100;, score=0.727 total time=   0.1s
[CV 2/5] END GBM__learning_rate=0.01, GBM__max_depth=3, GBM__n_estimators=100;, score=0.755 total time=   0.1s
[CV 3/5] END GBM__learning_rate=0.01, GBM__max_depth=3, GBM__n_estimators=100;, score=0.690 total time=   0.1s
[CV 4/5] END GBM__learning_rate=0.01, GBM__max_depth=3, GBM__n_estimators=100;, score=0.769 total time=   0.1s
[CV 5/5] END GBM__learning_rate=0.01, GBM__max_depth=3, GBM__n_estimators=100;, score=0.750 total time=   0.1s
[CV 1/5] END GBM__learning_rate=0.01, GBM__max_depth=4, GBM__n_estimators=25;, score=0.330 total time=   0.0s
[CV 2/5] END GBM__learning_rate=0.01, GBM__max_depth=4, GBM__n_estimators=25;, score=0.343 total time=   0.0s
[CV 3/5] END GBM__learning_rate=0.01, GBM__max_depth=4, GBM__n_estimators=25;, score=0.312 total time=   0.0s
[CV 4/5] END GBM__learning_rate=0.01, GBM__max_depth=4, GBM__n_estimators=25;, score=0.349 total time=   0.0s
[CV 5/5] END GBM__learning_rate=0.01, GBM__max_depth=4, GBM__n_estimators=25;, score=0.336 total time=   0.0s
[CV 1/5] END GBM__learning_rate=0.01, GBM__max_depth=4, GBM__n_estimators=50;, score=0.532 total time=   0.0s
[CV 2/5] END GBM__learning_rate=0.01, GBM__max_depth=4, GBM__n_estimators=50;, score=0.554 total time=   0.0s
[CV 3/5] END GBM__learning_rate=0.01, GBM__max_depth=4, GBM__n_estimators=50;, score=0.504 total time=   0.0s
[CV 4/5] END GBM__learning_rate=0.01, GBM__max_depth=4, GBM__n_estimators=50;, score=0.564 total time=   0.0s
[CV 5/5] END GBM__learning_rate=0.01, GBM__max_depth=4, GBM__n_estimators=50;, score=0.545 total time=   0.0s
[CV 1/5] END GBM__learning_rate=0.01, GBM__max_depth=4, GBM__n_estimators=100;, score=0.731 total time=   0.1s
[CV 2/5] END GBM__learning_rate=0.01, GBM__max_depth=4, GBM__n_estimators=100;, score=0.759 total time=   0.1s
[CV 3/5] END GBM__learning_rate=0.01, GBM__max_depth=4, GBM__n_estimators=100;, score=0.695 total time=   0.1s
[CV 4/5] END GBM__learning_rate=0.01, GBM__max_depth=4, GBM__n_estimators=100;, score=0.772 total time=   0.1s
[CV 5/5] END GBM__learning_rate=0.01, GBM__max_depth=4, GBM__n_estimators=100;, score=0.755 total time=   0.1s
[CV 1/5] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=None, GBM__n_estimators=25;, score=0.834 total time=   0.0s
[CV 2/5] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=None, GBM__n_estimators=25;, score=0.864 total time=   0.0s
[CV 3/5] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=None, GBM__n_estimators=25;, score=0.792 total time=   0.0s
[CV 4/5] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=None, GBM__n_estimators=25;, score=0.881 total time=   0.0s
[CV 5/5] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=None, GBM__n_estimators=25;, score=0.867 total time=   0.0s
[CV 1/5] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=None, GBM__n_estimators=50;, score=0.829 total time=   0.0s
[CV 2/5] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=None, GBM__n_estimators=50;, score=0.862 total time=   0.0s
[CV 3/5] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=None, GBM__n_estimators=50;, score=0.783 total time=   0.1s
[CV 4/5] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=None, GBM__n_estimators=50;, score=0.880 total time=   0.1s
[CV 5/5] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=None, GBM__n_estimators=50;, score=0.862 total time=   0.0s
[CV 1/5] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=None, GBM__n_estimators=100;, score=0.826 total time=   0.2s
[CV 2/5] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=None, GBM__n_estimators=100;, score=0.847 total time=   0.2s
[CV 3/5] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=None, GBM__n_estimators=100;, score=0.760 total time=   0.2s
[CV 4/5] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=None, GBM__n_estimators=100;, score=0.866 total time=   0.1s
[CV 5/5] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=None, GBM__n_estimators=100;, score=0.852 total time=   0.2s
[CV 1/5] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=2, GBM__n_estimators=25;, score=0.825 total time=   0.0s
[CV 2/5] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=2, GBM__n_estimators=25;, score=0.860 total time=   0.0s
[CV 3/5] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=2, GBM__n_estimators=25;, score=0.795 total time=   0.0s
[CV 4/5] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=2, GBM__n_estimators=25;, score=0.883 total time=   0.0s
[CV 5/5] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=2, GBM__n_estimators=25;, score=0.866 total time=   0.0s
[CV 1/5] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=2, GBM__n_estimators=50;, score=0.838 total time=   0.0s
[CV 2/5] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=2, GBM__n_estimators=50;, score=0.874 total time=   0.0s
[CV 3/5] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=2, GBM__n_estimators=50;, score=0.810 total time=   0.0s
[CV 4/5] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=2, GBM__n_estimators=50;, score=0.893 total time=   0.0s
[CV 5/5] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=2, GBM__n_estimators=50;, score=0.882 total time=   0.0s
[CV 1/5] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=2, GBM__n_estimators=100;, score=0.840 total time=   0.1s
[CV 2/5] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=2, GBM__n_estimators=100;, score=0.876 total time=   0.1s
[CV 3/5] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=2, GBM__n_estimators=100;, score=0.812 total time=   0.1s
[CV 4/5] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=2, GBM__n_estimators=100;, score=0.894 total time=   0.1s
[CV 5/5] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=2, GBM__n_estimators=100;, score=0.883 total time=   0.1s
[CV 1/5] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=3, GBM__n_estimators=25;, score=0.840 total time=   0.0s
[CV 2/5] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=3, GBM__n_estimators=25;, score=0.874 total time=   0.0s
[CV 3/5] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=3, GBM__n_estimators=25;, score=0.813 total time=   0.0s
[CV 4/5] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=3, GBM__n_estimators=25;, score=0.889 total time=   0.0s
[CV 5/5] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=3, GBM__n_estimators=25;, score=0.883 total time=   0.0s
[CV 1/5] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=3, GBM__n_estimators=50;, score=0.843 total time=   0.0s
[CV 2/5] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=3, GBM__n_estimators=50;, score=0.878 total time=   0.0s
[CV 3/5] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=3, GBM__n_estimators=50;, score=0.818 total time=   0.0s
[CV 4/5] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=3, GBM__n_estimators=50;, score=0.892 total time=   0.0s
[CV 5/5] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=3, GBM__n_estimators=50;, score=0.886 total time=   0.0s
[CV 1/5] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=3, GBM__n_estimators=100;, score=0.838 total time=   0.1s
[CV 2/5] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=3, GBM__n_estimators=100;, score=0.873 total time=   0.1s
[CV 3/5] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=3, GBM__n_estimators=100;, score=0.814 total time=   0.1s
[CV 4/5] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=3, GBM__n_estimators=100;, score=0.887 total time=   0.1s
[CV 5/5] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=3, GBM__n_estimators=100;, score=0.880 total time=   0.1s
[CV 1/5] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=4, GBM__n_estimators=25;, score=0.839 total time=   0.0s
[CV 2/5] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=4, GBM__n_estimators=25;, score=0.875 total time=   0.0s
[CV 3/5] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=4, GBM__n_estimators=25;, score=0.813 total time=   0.0s
[CV 4/5] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=4, GBM__n_estimators=25;, score=0.889 total time=   0.0s
[CV 5/5] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=4, GBM__n_estimators=25;, score=0.882 total time=   0.0s
[CV 1/5] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=4, GBM__n_estimators=50;, score=0.837 total time=   0.0s
[CV 2/5] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=4, GBM__n_estimators=50;, score=0.877 total time=   0.0s
[CV 3/5] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=4, GBM__n_estimators=50;, score=0.812 total time=   0.0s
[CV 4/5] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=4, GBM__n_estimators=50;, score=0.891 total time=   0.0s
[CV 5/5] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=4, GBM__n_estimators=50;, score=0.880 total time=   0.0s
[CV 1/5] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=4, GBM__n_estimators=100;, score=0.832 total time=   0.1s
[CV 2/5] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=4, GBM__n_estimators=100;, score=0.870 total time=   0.1s
[CV 3/5] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=4, GBM__n_estimators=100;, score=0.808 total time=   0.1s
[CV 4/5] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=4, GBM__n_estimators=100;, score=0.882 total time=   0.1s
[CV 5/5] END GBM__learning_rate=0.10888888888888888, GBM__max_depth=4, GBM__n_estimators=100;, score=0.874 total time=   0.1s
[CV 1/5] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=None, GBM__n_estimators=25;, score=0.829 total time=   0.0s
[CV 2/5] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=None, GBM__n_estimators=25;, score=0.862 total time=   0.0s
[CV 3/5] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=None, GBM__n_estimators=25;, score=0.780 total time=   0.0s
[CV 4/5] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=None, GBM__n_estimators=25;, score=0.878 total time=   0.0s
[CV 5/5] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=None, GBM__n_estimators=25;, score=0.862 total time=   0.0s
[CV 1/5] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=None, GBM__n_estimators=50;, score=0.827 total time=   0.0s
[CV 2/5] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=None, GBM__n_estimators=50;, score=0.845 total time=   0.0s
[CV 3/5] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=None, GBM__n_estimators=50;, score=0.761 total time=   0.0s
[CV 4/5] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=None, GBM__n_estimators=50;, score=0.860 total time=   0.0s
[CV 5/5] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=None, GBM__n_estimators=50;, score=0.852 total time=   0.0s
[CV 1/5] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=None, GBM__n_estimators=100;, score=0.820 total time=   0.1s
[CV 2/5] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=None, GBM__n_estimators=100;, score=0.831 total time=   0.2s
[CV 3/5] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=None, GBM__n_estimators=100;, score=0.752 total time=   0.2s
[CV 4/5] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=None, GBM__n_estimators=100;, score=0.837 total time=   0.2s
[CV 5/5] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=None, GBM__n_estimators=100;, score=0.832 total time=   0.2s
[CV 1/5] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=2, GBM__n_estimators=25;, score=0.838 total time=   0.0s
[CV 2/5] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=2, GBM__n_estimators=25;, score=0.873 total time=   0.0s
[CV 3/5] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=2, GBM__n_estimators=25;, score=0.809 total time=   0.0s
[CV 4/5] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=2, GBM__n_estimators=25;, score=0.893 total time=   0.0s
[CV 5/5] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=2, GBM__n_estimators=25;, score=0.881 total time=   0.0s
[CV 1/5] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=2, GBM__n_estimators=50;, score=0.840 total time=   0.0s
[CV 2/5] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=2, GBM__n_estimators=50;, score=0.874 total time=   0.0s
[CV 3/5] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=2, GBM__n_estimators=50;, score=0.811 total time=   0.0s
[CV 4/5] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=2, GBM__n_estimators=50;, score=0.894 total time=   0.0s
[CV 5/5] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=2, GBM__n_estimators=50;, score=0.883 total time=   0.0s
[CV 1/5] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=2, GBM__n_estimators=100;, score=0.840 total time=   0.1s
[CV 2/5] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=2, GBM__n_estimators=100;, score=0.870 total time=   0.1s
[CV 3/5] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=2, GBM__n_estimators=100;, score=0.809 total time=   0.1s
[CV 4/5] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=2, GBM__n_estimators=100;, score=0.891 total time=   0.1s
[CV 5/5] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=2, GBM__n_estimators=100;, score=0.881 total time=   0.1s
[CV 1/5] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=3, GBM__n_estimators=25;, score=0.843 total time=   0.0s
[CV 2/5] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=3, GBM__n_estimators=25;, score=0.876 total time=   0.0s
[CV 3/5] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=3, GBM__n_estimators=25;, score=0.818 total time=   0.0s
[CV 4/5] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=3, GBM__n_estimators=25;, score=0.891 total time=   0.0s
[CV 5/5] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=3, GBM__n_estimators=25;, score=0.885 total time=   0.0s
[CV 1/5] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=3, GBM__n_estimators=50;, score=0.840 total time=   0.0s
[CV 2/5] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=3, GBM__n_estimators=50;, score=0.873 total time=   0.0s
[CV 3/5] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=3, GBM__n_estimators=50;, score=0.816 total time=   0.0s
[CV 4/5] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=3, GBM__n_estimators=50;, score=0.888 total time=   0.0s
[CV 5/5] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=3, GBM__n_estimators=50;, score=0.879 total time=   0.0s
[CV 1/5] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=3, GBM__n_estimators=100;, score=0.831 total time=   0.1s
[CV 2/5] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=3, GBM__n_estimators=100;, score=0.862 total time=   0.1s
[CV 3/5] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=3, GBM__n_estimators=100;, score=0.811 total time=   0.1s
[CV 4/5] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=3, GBM__n_estimators=100;, score=0.880 total time=   0.1s
[CV 5/5] END GBM__learning_rate=0.20777777777777778, GBM__max_depth=3, GBM__n_estimators=100;, score=0.869 total time=   0.1s

GridSearchCV(cv=KFold(n_splits=5, random_state=26, shuffle=True),
             estimator=Pipeline(steps=[('OHE',
                                        ColumnTransformer(transformers=[('onehotencoder',
                                                                         OneHotEncoder(drop='first',
                                                                                       sparse_output=False),
                                                                         <sklearn.compose._column_transformer.make_column_selector object at 0x0000016C688E5FD0>),
                                                                        ('passthrough',
                                                                         'passthrough',
                                                                         <sklearn.compose._column_transformer.make_...
                                                     min_child_weight=None,
                                                     missing=nan,
                                                     monotone_constraints=None,
                                                     multi_strategy=None,
                                                     n_estimators=None,
                                                     n_jobs=None,
                                                     num_parallel_tree=None, ...))]),
             param_grid={'GBM__learning_rate': array([0.01      , 0.10888889, 0.20777778, 0.30666667, 0.40555556,
       0.50444444, 0.60333333, 0.70222222, 0.80111111, 0.9       ]),
                         'GBM__max_depth': [None, 2, 3, 4],
                         'GBM__n_estimators': [25, 50, 100]},
             scoring='r2', verbose=3)

# n_jobs 
default=None\
n_jobs = -1 -> to speeding the run\
note -> don't use with verbose

In [35]:
gcv = GridSearchCV(pipe, param_grid=params,cv=kfold,scoring='r2',n_jobs=-1)
gcv.fit(X,y)

GridSearchCV(cv=KFold(n_splits=5, random_state=26, shuffle=True),
             estimator=Pipeline(steps=[('OHE',
                                        ColumnTransformer(transformers=[('onehotencoder',
                                                                         OneHotEncoder(drop='first',
                                                                                       sparse_output=False),
                                                                         <sklearn.compose._column_transformer.make_column_selector object at 0x0000016C688E5FD0>),
                                                                        ('passthrough',
                                                                         'passthrough',
                                                                         <sklearn.compose._column_transformer.make_...
                                                     min_child_weight=None,
                                                     missing=nan,
                                                     monotone_constraints=None,
                                                     multi_strategy=None,
                                                     n_estimators=None,
                                                     n_jobs=None,
                                                     num_parallel_tree=None, ...))]),
             n_jobs=-1,
             param_grid={'GBM__learning_rate': array([0.01      , 0.10888889, 0.20777778, 0.30666667, 0.40555556,
       0.50444444, 0.60333333, 0.70222222, 0.80111111, 0.9       ]),
                         'GBM__max_depth': [None, 2, 3, 4],
                         'GBM__n_estimators': [25, 50, 100]},
             scoring='r2')

# Exercise

In [36]:
df = pd.read_csv(r"C:\Users\PGCP-AI.STUDENTSDC\Desktop\Machine_Learning\Cases\Chemical_Process_Data\ChemicalProcess.csv")
df.sample(5)

,Yield,BiologicalMaterial01,BiologicalMaterial02,BiologicalMaterial03,BiologicalMaterial04,BiologicalMaterial05,BiologicalMaterial06,BiologicalMaterial07,BiologicalMaterial08,BiologicalMaterial09,...,ManufacturingProcess36,ManufacturingProcess37,ManufacturingProcess38,ManufacturingProcess39,ManufacturingProcess40,ManufacturingProcess41,ManufacturingProcess42,ManufacturingProcess43,ManufacturingProcess44,ManufacturingProcess45
38,42.23,5.32,59.14,71.05,13.02,21.17,52.58,100.0,16.94,12.32,...,0.019,0.0,2,7.1,0.1,0.2,11.0,1.5,1.8,2.4
35,40.87,6.30,57.04,70.03,11.70,18.04,50.50,100.0,17.27,12.79,...,0.020,1.0,2,7.4,0.1,0.2,11.0,0.9,2.0,2.1
126,42.28,6.23,52.95,66.71,12.75,16.31,45.84,100.0,16.70,12.75,...,0.020,1.0,3,7.2,0.0,0.0,11.4,0.6,1.9,2.2
81,41.25,8.81,63.99,78.25,23.09,19.96,53.87,100.0,18.84,14.08,...,0.019,0.2,3,7.1,0.0,0.0,11.6,1.2,1.9,2.2
19,39.53,7.51,59.74,67.28,15.72,21.80,52.30,100.0,18.81,12.98,...,0.020,1.2,2,7.3,0.0,0.0,11.4,1.5,1.5,2.0

In [37]:
df.isnull().sum().sum()

np.int64(106)

In [38]:
X , y = df.drop('Yield',axis=1) , df['Yield']

In [39]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler , MinMaxScaler

impute = SimpleImputer()
scl_scaler = StandardScaler()
mm_scaler = MinMaxScaler()
knn = KNeighborsRegressor()

kfold = KFold(n_splits=5, shuffle=True, random_state=26)

pipe = Pipeline([('IMP',impute),('SCL',None),('KNN',knn)])
# pipe.get_params()

In [40]:
params = {'IMP__strategy':['mean','median'],'SCL':[scl_scaler,mm_scaler,None],
          'KNN__n_neighbors':np.arange(1,11)}
gcv = GridSearchCV(pipe, param_grid=params, cv=kfold, scoring='r2', n_jobs=-1)
gcv.fit(X,y)

GridSearchCV(cv=KFold(n_splits=5, random_state=26, shuffle=True),
             estimator=Pipeline(steps=[('IMP', SimpleImputer()), ('SCL', None),
                                       ('KNN', KNeighborsRegressor())]),
             n_jobs=-1,
             param_grid={'IMP__strategy': ['mean', 'median'],
                         'KNN__n_neighbors': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
                         'SCL': [StandardScaler(), MinMaxScaler(), None]},
             scoring='r2')

In [41]:
print('Best Params ->',gcv.best_params_)
print('Best Score ->',gcv.best_score_)

Best Params -> {'IMP__strategy': 'mean', 'KNN__n_neighbors': np.int64(2), 'SCL': StandardScaler()}
Best Score -> 0.5092484572934366

# Exercise

In [42]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
cirrhosis_patient_survival_prediction = fetch_ucirepo(id=878) 
  
# data (as pandas dataframes) 
X = cirrhosis_patient_survival_prediction.data.features 
y = cirrhosis_patient_survival_prediction.data.targets 
  
# # metadata 
# print(cirrhosis_patient_survival_prediction.metadata) 
  
# # variable information 
# print(cirrhosis_patient_survival_prediction.variables)

In [43]:
X.sample(5)

,Drug,Age,Sex,Ascites,Hepatomegaly,Spiders,Edema,Bilirubin,Cholesterol,Albumin,Copper,Alk_Phos,SGOT,Tryglicerides,Platelets,Prothrombin,Stage
212,D-penicillamine,18337,F,N,N,Y,N,0.5,400,3.40,9,1134.0,96.10,55,356,10.2,3.0
219,D-penicillamine,23241,F,N,N,Y,N,3.8,426,3.22,96,2716.0,210.80,113,228,10.6,2.0
46,Placebo,17323,F,N,N,N,N,0.5,316,3.65,68,1716.0,187.55,71,356,9.8,3.0
177,D-penicillamine,25569,F,N,N,N,N,0.6,NaNN,4.08,51,665.0,74.40,NaNN,325,10.2,4.0
371,NaN,13514,F,NaN,NaN,NaN,N,0.6,NaN,3.55,NaN,NaN,NaN,NaN,248,10.3,2.0

In [44]:
y.sample(5)

    Status
279      C
395      C
298      C
48       D
273     CL

In [45]:
X.columns

Index(['Drug', 'Age', 'Sex', 'Ascites', 'Hepatomegaly', 'Spiders', 'Edema',
       'Bilirubin', 'Cholesterol', 'Albumin', 'Copper', 'Alk_Phos', 'SGOT',
       'Tryglicerides', 'Platelets', 'Prothrombin', 'Stage'],
      dtype='object')

In [46]:
X = X.replace('NaNN', np.nan)
X['Cholesterol'] = X['Cholesterol'].astype(float)
X['Copper'] = X['Copper'].astype(float)
X['Tryglicerides'] = X['Tryglicerides'].astype(float)
X['Platelets'] = X['Platelets'].astype(float)

In [47]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Drug           312 non-null    object
 1   Age            418 non-null    int64
 2   Sex            418 non-null    object
 3   Ascites        312 non-null    object
 4   Hepatomegaly   312 non-null    object
 5   Spiders        312 non-null    object
 6   Edema          418 non-null    object
 7   Bilirubin      418 non-null    float64
 8   Cholesterol    284 non-null    float64
 9   Albumin        418 non-null    float64
 10  Copper         310 non-null    float64
 11  Alk_Phos       312 non-null    float64
 12  SGOT           312 non-null    float64
 13  Tryglicerides  282 non-null    float64
 14  Platelets      407 non-null    float64
 15  Prothrombin    416 non-null    float64
 16  Stage          412 non-null    float64
dtypes: float64(10), int64(1), object(6)
memory usage: 55.6+ KB

In [48]:
encoder = OneHotEncoder(sparse_output=False, drop='first')

ct = make_column_transformer((encoder,make_column_selector(dtype_include='object')),
                             ('passthrough',make_column_selector(dtype_include='number')),
                             verbose_feature_names_out=False).set_output(transform='pandas')

In [49]:
num_imp = SimpleImputer()
cat_imp = SimpleImputer(strategy='constant',fill_value='Unkown')

ct_impute= make_column_transformer((num_imp,make_column_selector(dtype_include='number')),
                             (cat_imp,make_column_selector(dtype_include='object')),
                             verbose_feature_names_out=False).set_output(transform='pandas')

In [50]:
from sklearn.neighbors import KNeighborsClassifier
scl_scaler = StandardScaler()
mm_scaler = MinMaxScaler()
knn = KNeighborsClassifier()

kfold = KFold(n_splits=5, shuffle=True, random_state=26)

pipe = Pipeline([('IMP',ct_impute),('OHE',ct),('SCL',None),('KNN',knn)])
# pipe.get_params()

In [51]:
params = {
    'IMP__simpleimputer-1__strategy':['mean','median'],
    'IMP__simpleimputer-2__strategy':['constant','most_frequent'],
    'SCL':[scl_scaler,mm_scaler,None],
    'KNN__n_neighbors':np.arange(1,11)
}
gcv = GridSearchCV(pipe, param_grid=params, cv=kfold, scoring='neg_log_loss', n_jobs=-1)
gcv.fit(X,y)

GridSearchCV(cv=KFold(n_splits=5, random_state=26, shuffle=True),
             estimator=Pipeline(steps=[('IMP',
                                        ColumnTransformer(transformers=[('simpleimputer-1',
                                                                         SimpleImputer(),
                                                                         <sklearn.compose._column_transformer.make_column_selector object at 0x0000016C68CA3DD0>),
                                                                        ('simpleimputer-2',
                                                                         SimpleImputer(fill_value='Unkown',
                                                                                       strategy='constant'),
                                                                         <sklearn.compose._column_tr...
                                                                         <sklearn.compose._column_transformer.make_column_selector object at 0x0000016C68CA3890>)],
                                                          verbose_feature_names_out=False)),
                                       ('SCL', None),
                                       ('KNN', KNeighborsClassifier())]),
             n_jobs=-1,
             param_grid={'IMP__simpleimputer-1__strategy': ['mean', 'median'],
                         'IMP__simpleimputer-2__strategy': ['constant',
                                                            'most_frequent'],
                         'KNN__n_neighbors': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
                         'SCL': [StandardScaler(), MinMaxScaler(), None]},
             scoring='neg_log_loss')

In [52]:
print('Best Params ->',gcv.best_params_)
print('Best Score ->',gcv.best_score_)

Best Params -> {'IMP__simpleimputer-1__strategy': 'mean', 'IMP__simpleimputer-2__strategy': 'constant', 'KNN__n_neighbors': np.int64(10), 'SCL': None}
Best Score -> -1.7238268147136417

# With RandomForestClassifier()

In [53]:
from sklearn.ensemble import RandomForestClassifier

forest = RandomForestClassifier(random_state=26)
pipe = Pipeline([('IMP',ct_impute),('OHE',ct),('RF',forest)])
pipe.get_params()

{'memory': None,
 'steps': [('IMP',
   ColumnTransformer(transformers=[('simpleimputer-1', SimpleImputer(),
                                    <sklearn.compose._column_transformer.make_column_selector object at 0x0000016C68CA3DD0>),
                                   ('simpleimputer-2',
                                    SimpleImputer(fill_value='Unkown',
                                                  strategy='constant'),
                                    <sklearn.compose._column_transformer.make_column_selector object at 0x0000016C68CA3F50>)],
                     verbose_feature_names_out=False)),
  ('OHE',
   ColumnTransformer(transformers=[('onehotencoder',
                                    OneHotEncoder(drop='first',
                                                  sparse_output=False),
                                    <sklearn.compose._column_transformer.make_column_selector object at 0x0000016C689B72F0>),
                                   ('passthrough', 'passthrough',
                                    <sklearn.compose._column_transformer.make_column_selector object at 0x0000016C68CA3890>)],
                     verbose_feature_names_out=False)),
  ('RF', RandomForestClassifier(random_state=26))],
 'transform_input': None,
 'verbose': False,
 'IMP': ColumnTransformer(transformers=[('simpleimputer-1', SimpleImputer(),
                                  <sklearn.compose._column_transformer.make_column_selector object at 0x0000016C68CA3DD0>),
                                 ('simpleimputer-2',
                                  SimpleImputer(fill_value='Unkown',
                                                strategy='constant'),
                                  <sklearn.compose._column_transformer.make_column_selector object at 0x0000016C68CA3F50>)],
                   verbose_feature_names_out=False),
 'OHE': ColumnTransformer(transformers=[('onehotencoder',
                                  OneHotEncoder(drop='first',
                                                sparse_output=False),
                                  <sklearn.compose._column_transformer.make_column_selector object at 0x0000016C689B72F0>),
                                 ('passthrough', 'passthrough',
                                  <sklearn.compose._column_transformer.make_column_selector object at 0x0000016C68CA3890>)],
                   verbose_feature_names_out=False),
 'RF': RandomForestClassifier(random_state=26),
 'IMP__n_jobs': None,
 'IMP__remainder': 'drop',
 'IMP__sparse_threshold': 0.3,
 'IMP__transformer_weights': None,
 'IMP__transformers': [('simpleimputer-1',
   SimpleImputer(),
   <sklearn.compose._column_transformer.make_column_selector at 0x16c68ca3dd0>),
  ('simpleimputer-2',
   SimpleImputer(fill_value='Unkown', strategy='constant'),
   <sklearn.compose._column_transformer.make_column_selector at 0x16c68ca3f50>)],
 'IMP__verbose': False,
 'IMP__verbose_feature_names_out': False,
 'IMP__simpleimputer-1': SimpleImputer(),
 'IMP__simpleimputer-2': SimpleImputer(fill_value='Unkown', strategy='constant'),
 'IMP__simpleimputer-1__add_indicator': False,
 'IMP__simpleimputer-1__copy': True,
 'IMP__simpleimputer-1__fill_value': None,
 'IMP__simpleimputer-1__keep_empty_features': False,
 'IMP__simpleimputer-1__missing_values': nan,
 'IMP__simpleimputer-1__strategy': 'mean',
 'IMP__simpleimputer-2__add_indicator': False,
 'IMP__simpleimputer-2__copy': True,
 'IMP__simpleimputer-2__fill_value': 'Unkown',
 'IMP__simpleimputer-2__keep_empty_features': False,
 'IMP__simpleimputer-2__missing_values': nan,
 'IMP__simpleimputer-2__strategy': 'constant',
 'OHE__n_jobs': None,
 'OHE__remainder': 'drop',
 'OHE__sparse_threshold': 0.3,
 'OHE__transformer_weights': None,
 'OHE__transformers': [('onehotencoder',
   OneHotEncoder(drop='first', sparse_output=False),
   <sklearn.compose._column_transformer.make_column_selector at 0x16c689b72f0>),
  ('passthrough',
   'passthrough',
   <sklearn.compose._column_transformer.make_column_selector at 0x16c68ca3890>)],
 'OHE__verbose': False,
 'OHE__verbose_feature_names_out': False,
 'OHE__onehotencoder': OneHotEncoder(drop='first', sparse_output=False),
 'OHE__passthrough': 'passthrough',
 'OHE__onehotencoder__categories': 'auto',
 'OHE__onehotencoder__drop': 'first',
 'OHE__onehotencoder__dtype': numpy.float64,
 'OHE__onehotencoder__feature_name_combiner': 'concat',
 'OHE__onehotencoder__handle_unknown': 'error',
 'OHE__onehotencoder__max_categories': None,
 'OHE__onehotencoder__min_frequency': None,
 'OHE__onehotencoder__sparse_output': False,
 'RF__bootstrap': True,
 'RF__ccp_alpha': 0.0,
 'RF__class_weight': None,
 'RF__criterion': 'gini',
 'RF__max_depth': None,
 'RF__max_features': 'sqrt',
 'RF__max_leaf_nodes': None,
 'RF__max_samples': None,
 'RF__min_impurity_decrease': 0.0,
 'RF__min_samples_leaf': 1,
 'RF__min_samples_split': 2,
 'RF__min_weight_fraction_leaf': 0.0,
 'RF__monotonic_cst': None,
 'RF__n_estimators': 100,
 'RF__n_jobs': None,
 'RF__oob_score': False,
 'RF__random_state': 26,
 'RF__verbose': 0,
 'RF__warm_start': False}

In [54]:
params = {
    'IMP__simpleimputer-1__strategy':['mean','median'],
    'IMP__simpleimputer-2__strategy':['constant','most_frequent'],
    'RF__max_depth':[None,4,5,6,7],
    'RF__max_samples':[150,200,300,500],
    'RF__n_estimators':[25,50,100,150,200]
    
}
kfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=26)
gcv = GridSearchCV(pipe, param_grid=params, cv=kfold, scoring='neg_log_loss', n_jobs=-1)
gcv.fit(X,y)

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=26, shuffle=True),
             estimator=Pipeline(steps=[('IMP',
                                        ColumnTransformer(transformers=[('simpleimputer-1',
                                                                         SimpleImputer(),
                                                                         <sklearn.compose._column_transformer.make_column_selector object at 0x0000016C68CA3DD0>),
                                                                        ('simpleimputer-2',
                                                                         SimpleImputer(fill_value='Unkown',
                                                                                       strategy='constant'),
                                                                         <sklearn.compose....
                                                                         <sklearn.compose._column_transformer.make_column_selector object at 0x0000016C68CA3890>)],
                                                          verbose_feature_names_out=False)),
                                       ('RF',
                                        RandomForestClassifier(random_state=26))]),
             n_jobs=-1,
             param_grid={'IMP__simpleimputer-1__strategy': ['mean', 'median'],
                         'IMP__simpleimputer-2__strategy': ['constant',
                                                            'most_frequent'],
                         'RF__max_depth': [None, 4, 5, 6, 7],
                         'RF__max_samples': [150, 200, 300, 500],
                         'RF__n_estimators': [25, 50, 100, 150, 200]},
             scoring='neg_log_loss')

In [55]:
print('Best Params ->',gcv.best_params_)
print('Best Score ->',gcv.best_score_)

Best Params -> {'IMP__simpleimputer-1__strategy': 'mean', 'IMP__simpleimputer-2__strategy': 'constant', 'RF__max_depth': 6, 'RF__max_samples': 300, 'RF__n_estimators': 50}
Best Score -> -0.6415293147157626

# RandomizedSearchCV()

In [66]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.preprocessing import OrdinalEncoder
from lightgbm import LGBMRegressor

In [67]:
from ISLP import load_data
df = load_data('Carseats')
df.columns

Index(['Sales', 'CompPrice', 'Income', 'Advertising', 'Population', 'Price',
       'ShelveLoc', 'Age', 'Education', 'Urban', 'US'],
      dtype='object')

In [68]:
X , y = df.drop('Sales',axis=1) , df['Sales']
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=26,test_size=0.2,stratify=df['ShelveLoc'])

In [69]:
ord_encoder = OrdinalEncoder(categories=[['Bad','Medium','Good']]).set_output(transform='pandas')
ohe_encoder = OneHotEncoder(sparse_output=False, drop='first')
ct= make_column_transformer((ord_encoder,['ShelveLoc']),
                            (ohe_encoder,['Urban','US']),
                             ('passthrough',make_column_selector(dtype_include='number')),
                             verbose_feature_names_out=False)

In [71]:
lgbm = LGBMRegressor(random_state=26,verbose=-1)
pipe = Pipeline([('OHE',ct),('LGBM',lgbm)])

params = {
    'LGBM__max_depth':[None,3,4,5,7],
    'LGBM__learning_rate':np.linspace(0.01,0.9,10),
    'LGBM__n_estimators':[25,50,100]
}

rcv = RandomizedSearchCV(pipe,param_distributions=params,cv=kfold,scoring='r2',n_jobs=-1)
rcv.fit(X_train,y_train)

ValueError: Supported target types are: ('binary', 'multiclass'). Got 'continuous' instead.