### Ridge Regression

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import Ridge
from sklearn.model_selection import train_test_split
from sklearn.metrics import root_mean_squared_error,r2_score

In [2]:
df = pd.read_csv(r"C:\Users\PGCP-AI.STUDENTSDC\Desktop\Machine_Learning\Datasets\housing.csv")
df.head()

,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,42000.0,5850,3,1,2,yes,no,yes,no,no,1,no
1,38500.0,4000,2,1,1,yes,no,no,no,no,0,no
2,49500.0,3060,3,1,1,yes,no,no,no,no,0,no
3,60500.0,6650,3,1,2,yes,yes,no,no,no,0,no
4,61000.0,6360,2,1,1,yes,no,no,no,no,0,no

In [3]:
X = df.drop('price',axis=1)
y = df['price']

In [4]:
encoder = OneHotEncoder(sparse_output = False,drop='first').set_output(transform='pandas')
numeric = X.select_dtypes(include='number')
category = X.select_dtypes(include=['object','str'])
X_encoded = encoder.fit_transform(category)
X_encoded = pd.concat([numeric,X_encoded],axis=1)
X_encoded.head()

,lotsize,bedrooms,bathrms,stories,garagepl,driveway_yes,recroom_yes,fullbase_yes,gashw_yes,airco_yes,prefarea_yes
0,5850,3,1,2,1,1.0,0.0,1.0,0.0,0.0,0.0
1,4000,2,1,1,0,1.0,0.0,0.0,0.0,0.0,0.0
2,3060,3,1,1,0,1.0,0.0,0.0,0.0,0.0,0.0
3,6650,3,1,2,0,1.0,1.0,0.0,0.0,0.0,0.0
4,6360,2,1,1,0,1.0,0.0,0.0,0.0,0.0,0.0

In [5]:
X_train,X_test,y_train,y_test = train_test_split(X_encoded,y,train_size=0.7,random_state=26)

In [6]:
model = Ridge() # default alpha = 1
model.fit(X_train,y_train)
model.coef_

array([4.56610469e+00, 2.06191429e+03, 1.33910373e+04, 6.02801491e+03,
       3.34603053e+03, 6.28094679e+03, 3.21975767e+03, 6.71200452e+03,
       1.04578147e+04, 1.23047338e+04, 9.41029097e+03])

In [7]:
y_pred = model.predict(X_test)
print('R2 Score ->',r2_score(y_test,y_pred))
print('RMSE ->',root_mean_squared_error(y_test,y_pred))

R2 Score -> 0.6784289744793978
RMSE -> 15070.47480878495

In [8]:
# Try For alpha = [0.1,0.25,0.7,1,1.5,2,5,10,50]
alpha = [0.1,0.25,0.7,1,1.5,2,5,10,50]
score =[]

In [9]:
for x in alpha:
    model = Ridge(alpha=x) 
    model.fit(X_train,y_train)
    y_pred = model.predict(X_test)
    print('R2 Score ->',r2_score(y_test,y_pred))
    print('RMSE ->',root_mean_squared_error(y_test,y_pred))
    score.append([x,r2_score(y_test,y_pred),root_mean_squared_error(y_test,y_pred)])

R2 Score -> 0.6791065537995606
RMSE -> 15054.589007441034
R2 Score -> 0.6789976120224888
RMSE -> 15057.144270758692
R2 Score -> 0.6786608730449469
RMSE -> 15065.03984806656
R2 Score -> 0.6784289744793978
RMSE -> 15070.47480878495
R2 Score -> 0.6780311442617772
RMSE -> 15079.794114038725
R2 Score -> 0.6776211496077685
RMSE -> 15089.39235292554
R2 Score -> 0.6749937971261597
RMSE -> 15150.756031047045
R2 Score -> 0.6703287867774149
RMSE -> 15259.10260185512
R2 Score -> 0.632982345203871
RMSE -> 16100.225467703773

In [10]:
scores = pd.DataFrame(score , columns=['Alpha','R2 Score','RMSE'])
scores

   Alpha  R2 Score          RMSE
0   0.10  0.679107  15054.589007
1   0.25  0.678998  15057.144271
2   0.70  0.678661  15065.039848
3   1.00  0.678429  15070.474809
4   1.50  0.678031  15079.794114
5   2.00  0.677621  15089.392353
6   5.00  0.674994  15150.756031
7  10.00  0.670329  15259.102602
8  50.00  0.632982  16100.225468

In [11]:
scores.sort_values('RMSE')

   Alpha  R2 Score          RMSE
0   0.10  0.679107  15054.589007
1   0.25  0.678998  15057.144271
2   0.70  0.678661  15065.039848
3   1.00  0.678429  15070.474809
4   1.50  0.678031  15079.794114
5   2.00  0.677621  15089.392353
6   5.00  0.674994  15150.756031
7  10.00  0.670329  15259.102602
8  50.00  0.632982  16100.225468

In [12]:
# excerices
import pandas as pd
import numpy as np

X = np.array([
    [-3, -2],
    [-3,  2],
    [-2, -2],
    [-2,  2],
    [ 2, -2],
    [ 2,  2],
    [ 3, -2],
    [ 3,  2]
])

y = 4 * X[:, 0] - 2 * X[:, 1]

In [13]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X,y)
lr.coef_

array([ 4., -2.])

In [14]:
from sklearn.linear_model import Ridge
ridge = Ridge(alpha=0.1)
ridge.fit(X,y)
ridge.coef_

array([ 3.99232246, -1.99376947])

In [15]:
model = Ridge(alpha=1)
model.fit(X,y)
model.coef_

array([ 3.9245283 , -1.93939394])

In [16]:
model = Ridge(alpha=100)
model.fit(X,y)
model.coef_

array([ 1.36842105, -0.48484848])

In [17]:
model = Ridge(alpha=500)
model.fit(X,y)
model.coef_

array([ 0.37681159, -0.12030075])

In [18]:
# Ridge generally shrinks coefficients without making them exactly zero.

# Lasso Regression

In [19]:
import pandas as pd
import numpy as np
from sklearn.linear_model import Lasso
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score,root_mean_squared_error

In [20]:
# Create dataset
from sklearn.datasets import make_regression
X, y = make_regression(
    n_samples=300,
    n_features=8,
    n_informative=3,
    noise=15,
    random_state=42
)

feature_names = [f"Feature_{i}" for i in range(1, 9)]

In [21]:
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=42,train_size=0.8)

In [22]:
model =  Lasso()

In [23]:
# Start Class Work From Here

In [35]:
alpha = [0.1,0.25,0.7,1,1.5,2,5,10,50]
score =[]
for x in alpha:
    model = Lasso(alpha=x) 
    model.fit(X_train,y_train)
    y_pred = model.predict(X_test)
    score.append([x,r2_score(y_test,y_pred),root_mean_squared_error(y_test,y_pred)])
df_score = pd.DataFrame(score, columns=['Alpha','R2 Score','RMSE'])
df_score.sort_values('RMSE')

   Alpha  R2 Score       RMSE
0   0.10  0.936914  13.860441
1   0.25  0.936361  13.921111
2   0.70  0.934180  14.157671
3   1.00  0.932331  14.355136
4   1.50  0.928689  14.736371
5   2.00  0.924448  15.168211
6   5.00  0.886654  18.578651
7  10.00  0.837184  22.266926
8  50.00  0.136487  51.279776

# Elastic Net Regression

In [29]:
from sklearn.linear_model import ElasticNet

In [37]:
alphas = [0.1,0.25,0.7,1,1.5,2,5,10,50]
ratios = [0.1,0.25,0.5,0.75,1]
scores = []
for a in alphas:
    for r in ratios:
        el = ElasticNet(alpha=a,l1_ratio=r)
        el.fit(X_train,y_train)
        y_pred = el.predict(X_test)
        scores.append([a,r,root_mean_squared_error(y_test,y_pred)])
df_score = pd.DataFrame(scores, columns=['Alpha','l1_ratio','RMSE'])
df_score.sort_values('RMSE')

    Alpha  l1_ratio       RMSE
4    0.10      1.00  13.860441
9    0.25      1.00  13.921111
14   0.70      1.00  14.157671
3    0.10      0.75  14.202392
19   1.00      1.00  14.355136
2    0.10      0.50  14.637614
24   1.50      1.00  14.736371
8    0.25      0.75  14.984332
1    0.10      0.25  15.142142
29   2.00      1.00  15.168211
0    0.10      0.10  15.469751
7    0.25      0.50  16.407261
6    0.25      0.25  17.960532
13   0.70      0.75  18.081633
34   5.00      1.00  18.578651
5    0.25      0.10  18.897605
18   1.00      0.75  20.283946
39  10.00      1.00  22.266926
12   0.70      0.50  22.345620
23   1.50      0.75  23.731340
17   1.00      0.50  25.785642
11   0.70      0.25  25.969347
28   2.00      0.75  26.756223
10   0.70      0.10  27.816856
16   1.00      0.25  29.965058
22   1.50      0.50  30.401421
15   1.00      0.10  31.963083
27   2.00      0.50  33.934035
21   1.50      0.25  34.848168
20   1.50      0.10  36.826070
33   5.00      0.75  38.251243
26   2.00      0.25  38.293816
25   2.00      0.10  40.139776
32   5.00      0.50  44.548933
38  10.00      0.75  46.045120
31   5.00      0.25  47.516902
30   5.00      0.10  48.610453
37  10.00      0.50  50.306248
44  50.00      1.00  51.279776
36  10.00      0.25  51.968964
35  10.00      0.10  52.531761
43  50.00      0.75  55.963936
42  50.00      0.50  56.134655
41  50.00      0.25  56.194359
40  50.00      0.10  56.211948