In [1]:
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\PGCP-AI.STUDENTSDC\Desktop\Machine_Learning\Datasets\Faceplate.csv",index_col=0)
df.head()

             Red  White  Blue  Orange  Green  Yellow
Transaction
1              1      1     0       0      1       0
2              0      1     0       1      0       0
3              0      1     1       0      0       0
4              1      1     0       1      0       0
5              1      0     1       0      0       0

In [5]:
df = df.astype(bool)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, 1 to 10
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Red     10 non-null     bool
 1   White   10 non-null     bool
 2   Blue    10 non-null     bool
 3   Orange  10 non-null     bool
 4   Green   10 non-null     bool
 5   Yellow  10 non-null     bool
dtypes: bool(6)
memory usage: 140.0 bytes

In [6]:
itemset = apriori(df,min_support=0.2,use_colnames=True)
itemset

    support             itemsets
0       0.6                (Red)
1       0.7              (White)
2       0.6               (Blue)
3       0.2             (Orange)
4       0.2              (Green)
5       0.4         (White, Red)
6       0.4          (Blue, Red)
7       0.2         (Green, Red)
8       0.4        (White, Blue)
9       0.2      (Orange, White)
10      0.2       (Green, White)
11      0.2   (White, Blue, Red)
12      0.2  (Green, White, Red)

In [13]:
rules = association_rules(itemset,metric='confidence',min_threshold=0.5)
rules = rules[['antecedents','consequents','support','confidence','lift']]
rules.sort_values(by=['confidence','lift','support'],ascending=False)

       antecedents   consequents  support  confidence      lift
15         (Green)  (White, Red)      0.2    1.000000  2.500000
4          (Green)         (Red)      0.2    1.000000  1.666667
12  (Green, White)         (Red)      0.2    1.000000  1.666667
7         (Orange)       (White)      0.2    1.000000  1.428571
8          (Green)       (White)      0.2    1.000000  1.428571
13    (Green, Red)       (White)      0.2    1.000000  1.428571
2           (Blue)         (Red)      0.4    0.666667  1.111111
3            (Red)        (Blue)      0.4    0.666667  1.111111
1            (Red)       (White)      0.4    0.666667  0.952381
6           (Blue)       (White)      0.4    0.666667  0.952381
0          (White)         (Red)      0.4    0.571429  0.952381
5          (White)        (Blue)      0.4    0.571429  0.952381
14    (White, Red)       (Green)      0.2    0.500000  2.500000
9    (White, Blue)         (Red)      0.2    0.500000  0.833333
10    (White, Red)        (Blue)      0.2    0.500000  0.833333
11     (Blue, Red)       (White)      0.2    0.500000  0.714286

In [15]:
relv_rules = rules[rules['lift']>1]
relv_rules.sort_values(by=['confidence','lift','support'],ascending=False)

       antecedents   consequents  support  confidence      lift
15         (Green)  (White, Red)      0.2    1.000000  2.500000
4          (Green)         (Red)      0.2    1.000000  1.666667
12  (Green, White)         (Red)      0.2    1.000000  1.666667
7         (Orange)       (White)      0.2    1.000000  1.428571
8          (Green)       (White)      0.2    1.000000  1.428571
13    (Green, Red)       (White)      0.2    1.000000  1.428571
2           (Blue)         (Red)      0.4    0.666667  1.111111
3            (Red)        (Blue)      0.4    0.666667  1.111111
14    (White, Red)       (Green)      0.2    0.500000  2.500000

# Exercise

In [17]:
df = pd.read_csv(r"C:\Users\PGCP-AI.STUDENTSDC\Desktop\Machine_Learning\Datasets\Cosmetics.csv",index_col=0)
df.head()

,Bag,Blush,Nail Polish,Brushes,Concealer,Eyebrow Pencils,Bronzer,Lip liner,Mascara,Eye shadow,Foundation,Lip Gloss,Lipstick,Eyeliner
Trans.,,,,,,,,,,,,,,
1,0,1,1,1,1,0,1,1,1,0,0,0,0,1
2,0,0,1,0,1,0,1,1,0,0,1,1,0,0
3,0,1,0,0,1,1,1,1,1,1,1,1,1,0
4,0,0,1,1,1,0,1,0,0,0,1,0,0,1
5,0,1,0,0,1,0,1,1,1,1,0,1,1,0

In [18]:
df = df.astype(bool)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 1 to 1000
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Bag              1000 non-null   bool
 1   Blush            1000 non-null   bool
 2   Nail Polish      1000 non-null   bool
 3   Brushes          1000 non-null   bool
 4   Concealer        1000 non-null   bool
 5   Eyebrow Pencils  1000 non-null   bool
 6   Bronzer          1000 non-null   bool
 7   Lip liner        1000 non-null   bool
 8   Mascara          1000 non-null   bool
 9   Eye shadow       1000 non-null   bool
 10  Foundation       1000 non-null   bool
 11  Lip Gloss        1000 non-null   bool
 12  Lipstick         1000 non-null   bool
 13  Eyeliner         1000 non-null   bool
dtypes: bool(14)
memory usage: 21.5 KB

In [21]:
itemsets = apriori(df,min_support=0.2,use_colnames=True)
itemsets

    support                  itemsets
0     0.363                   (Blush)
1     0.280             (Nail Polish)
2     0.442               (Concealer)
3     0.279                 (Bronzer)
4     0.234               (Lip liner)
5     0.357                 (Mascara)
6     0.381              (Eye shadow)
7     0.536              (Foundation)
8     0.490               (Lip Gloss)
9     0.322                (Lipstick)
10    0.457                (Eyeliner)
11    0.220        (Blush, Concealer)
12    0.204      (Mascara, Concealer)
13    0.201   (Eye shadow, Concealer)
14    0.231   (Foundation, Concealer)
15    0.218    (Lip Gloss, Concealer)
16    0.297     (Eyeliner, Concealer)
17    0.321     (Eye shadow, Mascara)
18    0.211  (Foundation, Eye shadow)
19    0.201   (Lip Gloss, Eye shadow)
20    0.356   (Foundation, Lip Gloss)
21    0.238    (Foundation, Eyeliner)
22    0.227     (Lip Gloss, Eyeliner)

In [22]:
rules = association_rules(itemsets,metric='confidence',min_threshold=0.5)
rules = rules[['antecedents','consequents','support','confidence','lift']]
rules.sort_values(by=['confidence','lift','support'],ascending=False)

     antecedents   consequents  support  confidence      lift
6      (Mascara)  (Eye shadow)    0.321    0.899160  2.359999
7   (Eye shadow)     (Mascara)    0.321    0.842520  2.359999
11   (Lip Gloss)  (Foundation)    0.356    0.726531  1.355468
5    (Concealer)    (Eyeliner)    0.297    0.671946  1.470341
10  (Foundation)   (Lip Gloss)    0.356    0.664179  1.355468
4     (Eyeliner)   (Concealer)    0.297    0.649891  1.470341
0        (Blush)   (Concealer)    0.220    0.606061  1.371178
1      (Mascara)   (Concealer)    0.204    0.571429  1.292825
8   (Eye shadow)  (Foundation)    0.211    0.553806  1.033220
2   (Eye shadow)   (Concealer)    0.201    0.527559  1.193573
9   (Eye shadow)   (Lip Gloss)    0.201    0.527559  1.076651
3    (Concealer)  (Foundation)    0.231    0.522624  0.975046
12    (Eyeliner)  (Foundation)    0.238    0.520788  0.971619

In [23]:
relv_rules = rules[rules['lift']>1]
relv_rules.sort_values(by=['confidence','lift','support'],ascending=False)

     antecedents   consequents  support  confidence      lift
6      (Mascara)  (Eye shadow)    0.321    0.899160  2.359999
7   (Eye shadow)     (Mascara)    0.321    0.842520  2.359999
11   (Lip Gloss)  (Foundation)    0.356    0.726531  1.355468
5    (Concealer)    (Eyeliner)    0.297    0.671946  1.470341
10  (Foundation)   (Lip Gloss)    0.356    0.664179  1.355468
4     (Eyeliner)   (Concealer)    0.297    0.649891  1.470341
0        (Blush)   (Concealer)    0.220    0.606061  1.371178
1      (Mascara)   (Concealer)    0.204    0.571429  1.292825
8   (Eye shadow)  (Foundation)    0.211    0.553806  1.033220
2   (Eye shadow)   (Concealer)    0.201    0.527559  1.193573
9   (Eye shadow)   (Lip Gloss)    0.201    0.527559  1.076651

In [24]:
from ipywidgets import interact
import ipywidgets as widgets

In [25]:
def gen_rules(min_support,min_confidence):
    itemsets = apriori(df,min_support=min_support,use_colnames=True)
    rules = association_rules(itemsets,metric='confidence',min_threshold=min_confidence)
    rules = rules[['antecedents','consequents','support','confidence','lift']]
    relv_rules = rules[rules['lift']>1]
    return relv_rules.sort_values(by=['confidence','lift','support'],ascending=False)

In [28]:
interact(gen_rules,
         min_support = widgets.FloatSlider(value=0.01,min=0,max=1,step=0.01,description='Min Support:'),
         min_confidence = widgets.FloatSlider(value=0.01,min=0,max=1,step=0.01,description='Min Confidence:'))

interactive(children=(FloatSlider(value=0.01, description='Min Support:', max=1.0, step=0.01), FloatSlider(val…

# Exercise

In [29]:
df = pd.read_csv(r"C:\Users\PGCP-AI.STUDENTSDC\Desktop\Machine_Learning\Datasets\Coursetopics.csv")
df.head()

   Intro  DataMining  Survey  Cat Data  Regression  Forecast  DOE  SW
0      1           1       0         0           0         0    0   0
1      0           0       1         0           0         0    0   0
2      0           1       0         1           1         0    0   1
3      1           0       0         0           0         0    0   0
4      1           1       0         0           0         0    0   0

In [35]:
df = df.astype(bool)

In [36]:
def gen_rules(min_support,min_confidence):
    itemsets = apriori(df,min_support=min_support,use_colnames=True)
    rules = association_rules(itemsets,metric='confidence',min_threshold=min_confidence)
    rules = rules[['antecedents','consequents','support','confidence','lift']]
    relv_rules = rules[rules['lift']>1]
    return relv_rules.sort_values(by=['confidence','lift','support'],ascending=False)

In [42]:
interact(gen_rules,
         min_support = widgets.FloatSlider(value=0.01,min=0.01,max=0.1,step=0.01,description='Min Support:'),
         min_confidence = widgets.FloatSlider(value=0.01,min=0,max=1,step=0.01,description='Min Confidence:'))

interactive(children=(FloatSlider(value=0.01, description='Min Support:', max=0.1, min=0.01, step=0.01), Float…

# TransactionEncoder

In [50]:
groceries = []
with open(r"C:\Users\PGCP-AI.STUDENTSDC\Desktop\Machine_Learning\Datasets\Groceries.csv",'r') as f:groceries = f.read()
groceries = groceries.split('\n')
groceries_list = []
for i in groceries:
    groceries_list.append(i.split(','))

In [52]:
groceries_list   # list of list because TransactionEncoder required input as list of list

[['citrus fruit', 'semi-finished bread', 'margarine', 'ready soups'],
 ['tropical fruit', 'yogurt', 'coffee'],
 ['whole milk'],
 ['pip fruit', 'yogurt', 'cream cheese', 'meat spreads'],
 ['other vegetables',
  'whole milk',
  'condensed milk',
  'long life bakery product'],
 ['whole milk', 'butter', 'yogurt', 'rice', 'abrasive cleaner'],
 ['rolls/buns'],
 ['other vegetables',
  'UHT-milk',
  'rolls/buns',
  'bottled beer',
  'liquor (appetizer)'],
 ['potted plants'],
 ['whole milk', 'cereals'],
 ['tropical fruit',
  'other vegetables',
  'white bread',
  'bottled water',
  'chocolate'],
 ['citrus fruit',
  'tropical fruit',
  'whole milk',
  'butter',
  'curd',
  'yogurt',
  'flour',
  'bottled water',
  'dishes'],
 ['beef'],
 ['frankfurter', 'rolls/buns', 'soda'],
 ['chicken', 'tropical fruit'],
 ['butter', 'sugar', 'fruit/vegetable juice', 'newspapers'],
 ['fruit/vegetable juice'],
 ['packaged fruit/vegetables'],
 ['chocolate'],
 ['specialty bar'],
 ['other vegetables'],
 ['butter milk', 'pastry'],
 ['whole milk'],
 ['tropical fruit',
  'cream cheese',
  'processed cheese',
  'detergent',
  'newspapers'],
 ['tropical fruit',
  'root vegetables',
  'other vegetables',
  'frozen dessert',
  'rolls/buns',
  'flour',
  'sweet spreads',
  'salty snack',
  'waffles',
  'candy',
  'bathroom cleaner'],
 ['bottled water', 'canned beer'],
 ['yogurt'],
 ['sausage', 'rolls/buns', 'soda', 'chocolate'],
 ['other vegetables'],
 ['brown bread',
  'soda',
  'fruit/vegetable juice',
  'canned beer',
  'newspapers',
  'shopping bags'],
 ['yogurt', 'beverages', 'bottled water', 'specialty bar'],
 ['hamburger meat',
  'other vegetables',
  'rolls/buns',
  'spices',
  'bottled water',
  'hygiene articles',
  'napkins'],
 ['root vegetables', 'other vegetables', 'whole milk', 'beverages', 'sugar'],
 ['pork',
  'berries',
  'other vegetables',
  'whole milk',
  'whipped/sour cream',
  'artif. sweetener',
  'soda',
  'abrasive cleaner'],
 ['beef', 'grapes', 'detergent'],
 ['pastry', 'soda'],
 ['fruit/vegetable juice'],
 ['canned beer'],
 ['root vegetables', 'other vegetables', 'whole milk', 'dessert'],
 ['citrus fruit', 'zwieback', 'newspapers'],
 ['sausage',
  'rolls/buns',
  'soda',
  'canned beer',
  'specialty bar',
  'shopping bags'],
 ['tropical fruit',
  'root vegetables',
  'whole milk',
  'yogurt',
  'domestic eggs',
  'brown bread',
  'pastry',
  'sugar',
  'cereals',
  'coffee',
  'soda',
  'waffles',
  'candy'],
 ['berries', 'yogurt'],
 ['canned beer'],
 ['butter milk',
  'yogurt',
  'cream cheese',
  'spread cheese',
  'rolls/buns',
  'bottled water',
  'soda',
  'newspapers'],
 ['coffee'],
 ['pastry', 'bottled water'],
 ['rolls/buns'],
 ['misc. beverages'],
 ['root vegetables',
  'other vegetables',
  'butter',
  'curd',
  'whipped/sour cream',
  'UHT-milk',
  'hard cheese',
  'rolls/buns',
  'bottled water',
  'long life bakery product'],
 ['sausage', 'rolls/buns', 'cat food', 'newspapers'],
 ['canned beer'],
 ['ham', 'grapes', 'other vegetables', 'whole milk'],
 ['turkey',
  'tropical fruit',
  'other vegetables',
  'curd',
  'domestic eggs',
  'brown bread',
  'semi-finished bread',
  'margarine',
  'baking powder',
  'fruit/vegetable juice'],
 ['whole milk', 'yogurt', 'processed cheese', 'pickled vegetables', 'soda'],
 ['whole milk', 'curd', 'yogurt', 'pastry'],
 ['packaged fruit/vegetables', 'brown bread', 'canned beer'],
 ['rolls/buns',
  'oil',
  'bottled water',
  'chewing gum',
  'chocolate marshmallow',
  'hygiene articles',
  'napkins'],
 ['ham', 'beef', 'whipped/sour cream', 'ice cream', 'rolls/buns', 'cat food'],
 ['rolls/buns', 'pastry', 'sugar'],
 ['other vegetables',
  'whole milk',
  'frozen vegetables',
  'canned fish',
  'salty snack',
  'seasonal products',
  'detergent'],
 ['sausage', 'pastry'],
 ['sausage', 'beef', 'whole milk'],
 ['frankfurter', 'tropical fruit', 'rolls/buns', 'brown bread', 'sugar'],
 ['rolls/buns', 'pastry', 'soda'],
 ['whole milk'],
 ['curd cheese', 'coffee'],
 ['red/blush wine', 'newspapers'],
 ['sausage', 'whole milk', 'curd'],
 ['tropical fruit',
  'pip fruit',
  'berries',
  'whole milk',
  'frozen potato products',
  'rolls/buns',
  'pickled vegetables',
  'chocolate'],
 ['red/blush wine'],
 ['whole milk',
  'butter',
  'margarine',
  'specialty fat',
  'specialty chocolate',
  'candles',
  'flower (seeds)'],
 ['frankfurter',
  'citrus fruit',
  'whole milk',
  'domestic eggs',
  'oil',
  'sparkling wine',
  'specialty chocolate',
  'newspapers'],
 ['whole milk', 'meat spreads', 'soda'],
 ['frozen potato products'],
 ['other vegetables', 'whole milk', 'rolls/buns', 'sugar'],
 ['citrus fruit', 'whole milk', 'curd', 'butter milk', 'pastry'],
 ['flour', 'salt', 'bottled water', 'fruit/vegetable juice', 'bottled beer'],
 ['sugar', 'bottled water', 'soda', 'bottled beer'],
 ['frozen meals', 'coffee'],
 ['chocolate'],
 ['root vegetables',
  'whole milk',
  'frozen vegetables',
  'domestic eggs',
  'rolls/buns',
  'oil',
  'margarine',
  'canned vegetables',
  'fruit/vegetable juice',
  'bathroom cleaner'],
 ['root vegetables', 'onions', 'hard cheese', 'frozen vegetables'],
 ['herbs',
  'condensed milk',
  'frozen vegetables',
  'salt',
  'oil',
  'white wine',
  'candles'],
 ['bottled water'],
 ['sausage',
  'root vegetables',
  'onions',
  'yogurt',
  'rolls/buns',
  'brandy',
  'detergent'],
 ['coffee', 'newspapers'],
 ['pork', 'other vegetables', 'whipped/sour cream'],
 ['berries', 'yogurt'],
 ['soda'],
 ['berries'],
 ['fruit/vegetable juice', 'salty snack', 'candles'],
 ['citrus fruit', 'butter milk', 'yogurt', 'cream cheese'],
 ['pork',
  'hamburger meat',
  'citrus fruit',
  'berries',
  'onions',
  'whipped/sour cream',
  'rice',
  'coffee',
  'chocolate'],
 ['detergent'],
 ['grapes', 'photo/film'],
 ['sausage',
  'sliced cheese',
  'rolls/buns',
  'brown bread',
  'fruit/vegetable juice',
  'canned beer',
  'red/blush wine',
  'waffles',
  'shopping bags'],
 ['chicken',
  'hamburger meat',
  'citrus fruit',
  'tropical fruit',
  'root vegetables',
  'other vegetables',
  'butter',
  'pasta',
  'oil',
  'detergent'],
 ['whole milk', 'yogurt', 'brown bread'],
 ['citrus fruit', 'tropical fruit'],
 ['soda', 'misc. beverages'],
 ['sausage',
  'pork',
  'grapes',
  'whole milk',
  'rolls/buns',
  'pastry',
  'soda',
  'specialty bar',
  'bathroom cleaner'],
 ['frankfurter', 'rolls/buns', 'bottled water'],
 ['sausage',
  'whole milk',
  'yogurt',
  'coffee',
  'fruit/vegetable juice',
  'bottled beer',
  'softener',
  'napkins',
  'photo/film',
  'shopping bags'],
 ['soda'],
 ['rolls/buns', 'fruit/vegetable juice'],
 ['beef',
  'citrus fruit',
  'berries',
  'root vegetables',
  'brown bread',
  'detergent'],
 ['whole milk',
  'whipped/sour cream',
  'rolls/buns',
  'soda',
  'waffles',
  'candy',
  'cling film/bags'],
 ['processed cheese'],
 ['tropical fruit', 'pip fruit'],
 ['frankfurter',
  'sausage',
  'root vegetables',
  'other vegetables',
  'rolls/buns',
  'oil',
  'pickled vegetables',
  'bottled beer',
  'chewing gum',
  'dishes'],
 ['packaged fruit/vegetables', 'bottled water'],
 ['whole milk',
  'dessert',
  'frozen vegetables',
  'rolls/buns',
  'margarine',
  'bottled water',
  'red/blush wine',
  'newspapers'],
 ['berries', 'whipped/sour cream'],
 ['citrus fruit', 'berries', 'UHT-milk', 'processed cheese'],
 ['tropical fruit', 'whole milk', 'yogurt'],
 ['hamburger meat',
  'whole milk',
  'frozen vegetables',
  'rolls/buns',
  'bottled beer',
  'sparkling wine'],
 ['hamburger meat',
  'other vegetables',
  'whole milk',
  'frozen vegetables',
  'domestic eggs',
  'soda',
  'dishes'],
 ['whole milk', 'cream cheese', 'soda'],
 ['fish',
  'other vegetables',
  'pastry',
  'margarine',
  'coffee',
  'long life bakery product',
  'male cosmetics',
  'shopping bags'],
 ['frankfurter', 'sausage', 'long life bakery product', 'waffles'],
 ['packaged fruit/vegetables',
  'dessert',
  'semi-finished bread',
  'canned beer'],
 ['pastry', 'soda'],
 ['other vegetables', 'red/blush wine'],
 ['misc. beverages'],
 ['frankfurter',
  'sausage',
  'citrus fruit',
  'tropical fruit',
  'pip fruit',
  'whole milk',
  'hard cheese',
  'cream cheese',
  'domestic eggs',
  'rice',
  'sugar',
  'canned fruit',
  'misc. beverages',
  'fruit/vegetable juice',
  'hygiene articles'],
 ['sparkling wine'],
 ['specialty bar'],
 ['sausage', 'butter milk', 'rolls/buns'],
 ['curd cheese'],
 ['frankfurter', 'dessert'],
 ['whole milk', 'yogurt', 'beverages', 'brown bread', 'shopping bags'],
 ['newspapers'],
 ['berries', 'soda'],
 ['curd', 'flour', 'liquor (appetizer)'],
 ['tropical fruit', 'other vegetables', 'coffee'],
 ['soda'],
 ['rolls/buns', 'Instant food products'],
 ['canned beer'],
 ['canned beer'],
 ['frankfurter', 'sausage', 'whole milk', 'rolls/buns', 'margarine'],
 ['other vegetables', 'misc. beverages', 'canned beer'],
 ['whole milk', 'frozen vegetables'],
 ['whole milk'],
 ['citrus fruit',
  'butter',
  'cream cheese',
  'white bread',
  'oil',
  'margarine',
  'newspapers'],
 ['frankfurter', 'rolls/buns'],
 ['frankfurter',
  'ham',
  'pip fruit',
  'other vegetables',
  'whole milk',
  'soft cheese',
  'frozen vegetables',
  'rolls/buns',
  'sugar',
  'baking powder'],
 ['butter milk', 'yogurt', 'honey', 'soda', 'detergent'],
 ['hamburger meat',
  'citrus fruit',
  'onions',
  'rolls/buns',
  'bottled water',
  'dental care'],
 ['pasta', 'popcorn'],
 ['other vegetables',
  'whole milk',
  'meat spreads',
  'cake bar',
  'chocolate',
  'shopping bags'],
 ['sausage',
  'pork',
  'citrus fruit',
  'dessert',
  'white bread',
  'dishes',
  'candles'],
 ['rolls/buns'],
 ['grapes', 'other vegetables', 'curd', 'dessert', 'yogurt', 'napkins'],
 ['root vegetables',
  'other vegetables',
  'whole milk',
  'yogurt',
  'beverages',
  'soft cheese',
  'frozen vegetables',
  'fruit/vegetable juice',
  'bottled beer'],
 ['coffee', 'shopping bags'],
 ['popcorn'],
 ['whole milk', 'rolls/buns', 'sugar', 'bottled water', 'soda'],
 ['tropical fruit',
  'other vegetables',
  'packaged fruit/vegetables',
  'whole milk',
  'snack products'],
 ['beef', 'herbs', 'flour', 'cling film/bags', 'flower soil/fertilizer'],
 ['whole milk', 'butter', 'dessert', 'rolls/buns'],
 ['frankfurter', 'soda', 'chewing gum'],
 ['tropical fruit', 'specialty cheese', 'bottled water'],
 ['canned beer'],
 ['finished products',
  'other vegetables',
  'frozen vegetables',
  'bottled beer'],
 ['beverages', 'soda'],
 ['hamburger meat', 'root vegetables', 'whole milk'],
 ['whole milk', 'pastry', 'long life bakery product'],
 ['finished products', 'white wine', 'shopping bags'],
 ['other vegetables'],
 ['ham',
  'tropical fruit',
  'other vegetables',
  'whole milk',
  'white bread',
  'brown bread',
  'fruit/vegetable juice',
  'bottled beer'],
 ['other vegetables'],
 ['curd', 'butter milk', 'cocoa drinks', 'salty snack', 'popcorn'],
 ['bottled beer'],
 ['curd',
  'dessert',
  'soda',
  'salty snack',
  'waffles',
  'cake bar',
  'chocolate',
  'shopping bags'],
 ['whole milk', 'cream cheese', 'cereals', 'dog food'],
 ['whole milk', 'salt'],
 ['dessert', 'ice cream'],
 ['sausage', 'soft cheese', 'coffee'],
 ['other vegetables', 'bottled water', 'waffles', 'dishes', 'shopping bags'],
 ['ham', 'whole milk', 'rolls/buns'],
 ['other vegetables', 'ice cream'],
 ['other vegetables', 'bottled water'],
 ['soda', 'bottled beer', 'white wine', 'prosecco'],
 ['herbs', 'candy'],
 ['frankfurter',
  'ham',
  'tropical fruit',
  'pip fruit',
  'root vegetables',
  'other vegetables',
  'whole milk',
  'butter',
  'curd',
  'yogurt',
  'whipped/sour cream',
  'soft cheese',
  'sliced cheese',
  'cream cheese',
  'frozen meals',
  'frozen fish',
  'domestic eggs',
  'white bread',
  'sugar',
  'cereals',
  'fruit/vegetable juice',
  'bottled beer',
  'waffles'],
 ['rolls/buns', 'canned beer'],
 ['curd',
  'cream cheese',
  'semi-finished bread',
  'zwieback',
  'cake bar',
  'specialty bar',
  'shopping bags'],
 ['frankfurter',
  'tropical fruit',
  'whole milk',
  'spread cheese',
  'margarine',
  'shopping bags'],
 ['other vegetables'],
 ['dog food'],
 ['specialty bar'],
 ['curd', 'salt', 'liquor (appetizer)', 'detergent', 'shopping bags'],
 ['frankfurter', 'rolls/buns'],
 ['soda'],
 ['beef',
  'berries',
  'root vegetables',
  'whole milk',
  'dessert',
  'spread cheese',
  'brown bread'],
 ['canned beer'],
 ['pork', 'beef', 'pip fruit', 'herbs', 'spices'],
 ['frankfurter', 'citrus fruit', 'UHT-milk', 'margarine', 'sugar'],
 ['sausage', 'bottled beer', 'liquor (appetizer)'],
 ['canned beer'],
 ['specialty chocolate'],
 ['curd', 'rolls/buns'],
 ['canned beer'],
 ['whole milk', 'bottled water', 'newspapers'],
 ['rolls/buns', 'chewing gum'],
 ['pork', 'root vegetables', 'other vegetables', 'whole milk', 'dishes'],
 ['citrus fruit', 'pastry'],
 ['potted plants'],
 ['rolls/buns', 'pastry', 'soda'],
 ['butter',
  'yogurt',
  'bottled water',
  'soda',
  'make up remover',
  'hygiene articles'],
 ['condensed milk', 'sugar', 'coffee', 'shopping bags'],
 ['sausage', 'other vegetables', 'yogurt', 'soda', 'shopping bags'],
 ['whole milk', 'beverages', 'UHT-milk', 'soda'],
 ['sausage', 'pork', 'beef', 'whole milk', 'rolls/buns', 'margarine'],
 ['beverages'],
 ['beverages', 'specialty bar'],
 ['bottled water', 'fruit/vegetable juice'],
 ['newspapers'],
 ['cleaner', 'female sanitary products'],
 ['sausage', 'soda', 'newspapers', 'shopping bags'],
 ['newspapers'],
 ['sausage',
  'beef',
  'citrus fruit',
  'other vegetables',
  'whole milk',
  'butter milk',
  'whipped/sour cream',
  'beverages',
  'hard cheese',
  'rolls/buns',
  'dish cleaner',
  'cookware'],
 ['misc. beverages', 'newspapers'],
 ['white wine'],
 ['sausage',
  'sliced cheese',
  'rolls/buns',
  'soda',
  'canned beer',
  'shopping bags'],
 ['meat', 'curd', 'bottled beer', 'cake bar'],
 ['frankfurter',
  'meat',
  'tropical fruit',
  'onions',
  'oil',
  'baking powder',
  'tea',
  'cling film/bags'],
 ['ice cream', 'rolls/buns', 'canned beer'],
 ['canned beer'],
 ['tropical fruit',
  'berries',
  'root vegetables',
  'other vegetables',
  'bottled water',
  'shopping bags'],
 ['meat',
  'citrus fruit',
  'other vegetables',
  'curd',
  'dessert',
  'butter milk',
  'beverages',
  'cream cheese',
  'rolls/buns',
  'brown bread',
  'tea',
  'bottled water'],
 ['whole milk', 'mustard', 'bottled water'],
 ['sausage',
  'beef',
  'beverages',
  'sliced cheese',
  'rolls/buns',
  'spices',
  'house keeping products',
  'flower (seeds)'],
 ['frankfurter',
  'sausage',
  'root vegetables',
  'butter',
  'curd',
  'sliced cheese',
  'rolls/buns',
  'salty snack',
  'long life bakery product'],
 ['meat', 'other vegetables', 'butter', 'rolls/buns'],
 ['root vegetables',
  'beverages',
  'Instant food products',
  'pickled vegetables',
  'detergent'],
 ['root vegetables',
  'herbs',
  'other vegetables',
  'whole milk',
  'sliced cheese',
  'rolls/buns'],
 ['whole milk', 'whipped/sour cream', 'semi-finished bread', 'margarine'],
 ['citrus fruit',
  'whole milk',
  'curd',
  'dessert',
  'yogurt',
  'whipped/sour cream',
  'frozen dessert',
  'rolls/buns',
  'salt',
  'sugar',
  'cereals',
  'canned vegetables',
  'canned fish',
  'skin care',
  'hygiene articles',
  'napkins'],
 ['citrus fruit',
  'curd',
  'pastry',
  'margarine',
  'sugar',
  'candy',
  'newspapers'],
 ['other vegetables',
  'whole milk',
  'bottled water',
  'soda',
  'misc. beverages',
  'bottled beer',
  'red/blush wine',
  'napkins'],
 ['citrus fruit', 'whole milk', 'rolls/buns'],
 ['sausage', 'oil', 'hygiene articles', 'napkins'],
 ['frankfurter',
  'beef',
  'hamburger meat',
  'grapes',
  'root vegetables',
  'whole milk',
  'butter',
  'frozen dessert',
  'potato products',
  'bottled water',
  'bottled beer'],
 ['hard cheese', 'rolls/buns', 'bottled water', 'newspapers'],
 ['cream cheese', 'rolls/buns', 'soda', 'chocolate'],
 ['turkey', 'beef', 'frozen vegetables', 'dishes', 'photo/film'],
 ['pork',
  'other vegetables',
  'whipped/sour cream',
  'rolls/buns',
  'soda',
  'shopping bags'],
 ['whole milk', 'beverages'],
 ['rolls/buns', 'soda'],
 ['sausage',
  'pip fruit',
  'whole milk',
  'curd',
  'yogurt',
  'sliced cheese',
  'rolls/buns',
  'bottled water',
  'hygiene articles'],
 ['ice cream'],
 ['liquor'],
 ['pip fruit', 'other vegetables', 'fruit/vegetable juice'],
 ['root vegetables', 'other vegetables', 'yogurt'],
 ['soda'],
 ['soda'],
 ['sausage',
  'citrus fruit',
  'tropical fruit',
  'other vegetables',
  'whole milk',
  'yogurt',
  'rolls/buns',
  'bottled water',
  'soda',
  'chocolate',
  'newspapers'],
 ['root vegetables', 'whole milk', 'pet care', 'detergent'],
 ['pork',
  'berries',
  'root vegetables',
  'other vegetables',
  'pastry',
  'specialty bar'],
 ['pork'],
 ['chocolate'],
 ['fruit/vegetable juice'],
 ['pickled vegetables', 'coffee'],
 ['bottled water'],
 ['frankfurter',
  'sausage',
  'butter',
  'whipped/sour cream',
  'rolls/buns',
  'margarine',
  'spices'],
 ['tropical fruit',
  'pip fruit',
  'onions',
  'other vegetables',
  'whole milk',
  'domestic eggs',
  'sugar',
  'soups',
  'tea',
  'soda',
  'hygiene articles',
  'napkins'],
 ['canned beer'],
 ['root vegetables'],
 ['meat', 'citrus fruit', 'berries', 'root vegetables', 'whole milk', 'soda'],
 ['frankfurter',
  'rolls/buns',
  'bottled water',
  'fruit/vegetable juice',
  'hygiene articles'],
 ['tropical fruit', 'margarine', 'rum'],
 ['tropical fruit',
  'root vegetables',
  'herbs',
  'whole milk',
  'butter milk',
  'whipped/sour cream',
  'flour',
  'hygiene articles'],
 ['citrus fruit',
  'pip fruit',
  'root vegetables',
  'other vegetables',
  'whole milk',
  'cream cheese',
  'domestic eggs',
  'brown bread',
  'margarine',
  'baking powder',
  'waffles'],
 ['hamburger meat',
  'other vegetables',
  'whole milk',
  'curd',
  'yogurt',
  'rolls/buns',
  'pastry',
  'semi-finished bread',
  'margarine',
  'bottled water',
  'fruit/vegetable juice'],
 ['chicken',
  'pip fruit',
  'other vegetables',
  'whole milk',
  'dessert',
  'yogurt',
  'whipped/sour cream',
  'rolls/buns',
  'pasta',
  'soda',
  'waffles'],
 ['chicken',
  'citrus fruit',
  'tropical fruit',
  'root vegetables',
  'whole milk',
  'frozen fish',
  'rolls/buns'],
 ['frankfurter',
  'citrus fruit',
  'onions',
  'other vegetables',
  'whole milk',
  'rolls/buns',
  'sugar',
  'soda'],
 ['canned beer'],
 ['turkey', 'pip fruit', 'salad dressing', 'pastry'],
 ['packaged fruit/vegetables',
  'whole milk',
  'curd',
  'yogurt',
  'domestic eggs',
  'brown bread',
  'mustard',
  'pickled vegetables',
  'bottled water',
  'misc. beverages'],
 ['pasta'],
 ['citrus fruit', 'tropical fruit'],
 ['sausage',
  'whole milk',
  'yogurt',
  'rolls/buns',
  'brown bread',
  'potted plants'],
 ['whole milk', 'frozen meals', 'pastry', 'fruit/vegetable juice', 'waffles'],
 ['canned beer'],
 ['citrus fruit', 'sugar', 'sauces'],
 ['liquor (appetizer)'],
 ['citrus fruit',
  'other vegetables',
  'rolls/buns',
  'salty snack',
  'shopping bags'],
 ['sausage'],
 ['chicken',
  'other vegetables',
  'whole milk',
  'vinegar',
  'oil',
  'bottled water',
  'canned beer',
  'napkins',
  'newspapers'],
 ['hamburger meat',
  'root vegetables',
  'other vegetables',
  'whole milk',
  'yogurt',
  'whipped/sour cream',
  'specialty cheese',
  'flour',
  'margarine'],
 ['sausage', 'pork', 'other vegetables', 'dessert', 'yogurt', 'oil', 'soda'],
 ['beef',
  'berries',
  'root vegetables',
  'whole milk',
  'whipped/sour cream',
  'abrasive cleaner'],
 ['citrus fruit', 'packaged fruit/vegetables', 'yogurt', 'bottled water'],
 ['UHT-milk', 'coffee'],
 ['candy'],
 ['newspapers'],
 ['beef', 'citrus fruit', 'other vegetables', 'yogurt'],
 ['sausage', 'rolls/buns'],
 ['frankfurter',
  'beef',
  'root vegetables',
  'curd',
  'dessert',
  'yogurt',
  'soft cheese',
  'rolls/buns',
  'mustard',
  'pickled vegetables',
  'canned beer',
  'hygiene articles',
  'napkins'],
 ['canned beer'],
 ['bottled beer'],
 ['onions', 'soda', 'chewing gum', 'chocolate', 'newspapers'],
 ['tropical fruit',

In [57]:
from mlxtend.preprocessing import TransactionEncoder
te = TransactionEncoder()
te_ary = te.fit(groceries_list).transform(groceries_list)
df = pd.DataFrame(te_ary,columns=te.columns_)
df

,Instant food products,UHT-milk,abrasive cleaner,artif. sweetener,baby cosmetics,baby food,bags,baking powder,bathroom cleaner,beef,...,turkey,vinegar,waffles,whipped/sour cream,whisky,white bread,white wine,whole milk,yogurt,zwieback
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9830,False,False,False,False,False,False,False,False,False,True,...,False,False,False,True,False,False,False,True,False,False
9831,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9832,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
9833,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9834,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False

In [59]:
def gen_rules(min_support,min_confidence):
    itemsets = apriori(df,min_support=min_support,use_colnames=True)
    rules = association_rules(itemsets,metric='confidence',min_threshold=min_confidence)
    rules = rules[['antecedents','consequents','support','confidence','lift']]
    relv_rules = rules[rules['lift']>1]
    return relv_rules.sort_values(by=['confidence','lift','support'],ascending=False)

In [60]:
interact(gen_rules,
         min_support = widgets.FloatSlider(value=0.01,min=0.01,max=0.1,step=0.01,description='Min Support:'),
         min_confidence = widgets.FloatSlider(value=0.01,min=0,max=1,step=0.01,description='Min Confidence:'))

interactive(children=(FloatSlider(value=0.01, description='Min Support:', max=0.1, min=0.01, step=0.01), Float…

# Exercise

In [76]:
f = open(r"C:\Users\PGCP-AI.STUDENTSDC\Desktop\Machine_Learning\Datasets\DataSetA.csv",'r')
data = f.read()
food = data.split()
food_item = []
for i in food:
    food_item.append(i.split(','))

In [77]:
food_item

[['Lassi', 'Coffee'],
 ['Powder', 'Butter', 'Yougurt', 'Ghee', 'Cheese', ''],
 ['Ghee', 'Coffee'],
 ['Powder', ''],
 ['Lassi', 'Tea'],
 ['Powder', 'Butter', 'Cheese', ''],
 ['Cheese', 'Tea'],
 ['Powder', 'Panner', 'Coffee'],
 ['Powder', 'Butter', 'Bread', ''],
 ['Cheese', 'Yougurt', 'Coffee'],
 ['Powder', 'Sugar', 'Butter', 'Sweet', ''],
 ['Sugar', 'Tea'],
 ['Powder', 'Ghee', 'Sweet', 'Panner', 'Milk', ''],
 ['Sweet', 'Coffee'],
 ['Powder', ''],
 ['Butter', 'Ghee', 'Panner', ''],
 ['Sweet', 'Tea'],
 ['Powder', 'Butter', 'Yougurt', 'Sugar', 'Cheese', ''],
 ['Panner', 'Ghee', ''],
 ['Milk', 'Panner', 'Tea'],
 ['Powder', 'Sweet', 'Bread', ''],
 ['Ghee', 'Coffee'],
 ['Powder', 'Milk', 'Yougurt', 'Lassi', 'Sugar', 'Butter', 'Panner', ''],
 ['Butter', 'Coffee'],
 ['Powder', 'Panner', 'Sweet', 'Ghee', 'Lassi', ''],
 ['Bread', 'Lassi', 'Coffee'],
 ['Powder', 'Tea'],
 ['Powder', 'Sweet', 'Ghee', 'Sugar', 'Panner', ''],
 ['Milk', 'Sweet', 'Butter', 'Sugar', 'Lassi', 'Panner', ''],
 ['Bread', 'Coffee'],
 ['Powder', 'Tea'],
 ['Powder', ''],
 ['Butter', 'Ghee', 'Milk', 'Cheese', ''],
 ['Bread', 'Coffee'],
 ['Powder', ''],
 ['Cheese', 'Tea'],
 ['Powder', 'Sweet', 'Lassi', 'Coffee'],
 ['Powder', 'Sugar', ''],
 ['Panner', 'Lassi', 'Butter', 'Cheese', 'Yougurt', 'Tea'],
 ['Powder', 'Milk', ''],
 ['Coffee'],
 ['Powder', 'Cheese', 'Tea'],
 ['Powder', 'Yougurt', 'Sugar', ''],
 ['Lassi', 'Ghee', 'Cheese', 'Sweet', 'Coffee'],
 ['Powder', 'Bread', ''],
 ['Coffee'],
 ['Powder', 'Panner', 'Butter', 'Ghee', 'Tea'],
 ['Powder', 'Yougurt', ''],
 ['Yougurt', 'Sweet', 'Milk', 'Butter', 'Coffee'],
 ['Powder', 'Lassi', ''],
 ['Sugar', 'Coffee'],
 ['Powder', 'Milk', 'Butter', 'Cheese', 'Yougurt', ''],
 ['Lassi', 'Yougurt', 'Ghee', 'Cheese', 'Butter', 'Milk', 'Panner', ''],
 ['Panner', 'Yougurt', 'Sugar', 'Coffee'],
 ['Powder', 'Milk', 'Cheese', ''],
 ['Panner', 'Milk', 'Sweet', ''],
 ['Bread', 'Coffee'],
 ['Powder', ''],
 ['Sweet', 'Cheese', ''],
 ['Yougurt', 'Bread', 'Tea'],
 ['Powder', 'Coffee'],
 ['Powder', ''],
 ['Lassi', 'Sweet', 'Panner', ''],
 ['Milk', 'Butter', 'Bread', 'Tea'],
 ['Powder', 'Panner', 'Ghee', ''],
 ['Butter', 'Cheese', 'Panner', 'Sugar', ''],
 ['Cheese', 'Yougurt', 'Sugar', 'Bread', 'Butter', 'Panner', ''],
 ['Lassi', 'Bread', 'Panner', 'Milk', ''],
 ['Ghee', 'Bread', 'Cheese', 'Sugar', 'Coffee'],
 ['Powder', 'Sweet', 'Yougurt', 'Lassi', ''],
 ['Bread', 'Yougurt', 'Ghee', 'Tea'],
 ['Powder', 'Panner', 'Milk', 'Lassi', 'Coffee'],
 ['Powder', ''],
 ['Sugar', 'Milk', 'Butter', 'Ghee', 'Cheese', ''],
 ['Cheese', 'Panner', 'Sugar', 'Yougurt', 'Ghee', ''],
 ['Sweet', 'Panner', 'Bread', ''],
 ['Coffee'],
 ['Powder', 'Milk', 'Bread', ''],
 ['Cheese', 'Lassi', 'Coffee'],
 ['Powder', 'Tea'],
 ['Powder', 'Bread', 'Panner', 'Butter', ''],
 ['Cheese', 'Tea'],
 ['Powder', 'Milk', 'Yougurt', 'Ghee', ''],
 ['Sugar', 'Yougurt', 'Bread', 'Butter', 'Ghee', 'Milk', 'Lassi', ''],
 ['Butter', 'Tea'],
 ['Powder', 'Cheese', 'Yougurt', 'Bread', 'Ghee', 'Coffee'],
 ['Powder', ''],
 ['Sugar', 'Milk', ''],
 ['Sweet', 'Butter', ''],
 ['Yougurt', 'Bread', 'Sweet', ''],
 ['Cheese', 'Coffee'],
 ['Powder', 'Butter', 'Sugar', 'Panner', 'Bread', 'Lassi', 'Tea'],
 ['Powder', 'Ghee', ''],
 ['Yougurt', 'Panner', 'Butter', 'Lassi', 'Sugar', 'Bread', 'Tea'],
 ['Powder', 'Milk', ''],
 ['Butter', 'Lassi', ''],
 ['Sugar', 'Panner', 'Tea'],
 ['Powder', 'Sweet', 'Coffee'],
 ['Powder', 'Cheese', 'Lassi', 'Milk', 'Butter', ''],
 ['Lassi', 'Butter', ''],
 ['Coffee'],
 ['Powder', 'Butter', 'Ghee', ''],
 ['Lassi', 'Butter', 'Bread', 'Ghee', 'Coffee'],
 ['Powder', ''],
 ['Butter', 'Sugar', 'Yougurt', ''],
 ['Lassi', 'Butter', ''],
 ['Ghee', 'Bread', 'Cheese', 'Lassi', 'Tea'],
 ['Powder', 'Coffee'],
 ['Powder', 'Sweet', 'Butter', ''],
 ['Panner', 'Milk', 'Bread', 'Yougurt', ''],
 ['Panner', 'Tea'],
 ['Powder', ''],
 ['Bread', 'Panner', ''],
 ['Yougurt', 'Sugar', 'Sweet', 'Ghee', 'Bread', 'Butter', 'Coffee'],
 ['Powder', 'Lassi', 'Tea'],
 ['Powder', 'Milk', 'Panner', ''],
 ['Tea'],
 ['Powder', 'Sweet', 'Lassi', 'Ghee', ''],
 ['Lassi', 'Coffee'],
 ['Powder', 'Sugar', ''],
 ['Cheese', 'Sugar', 'Tea'],
 ['Powder', 'Butter', ''],
 ['Bread', 'Yougurt', 'Milk', 'Panner', 'Sweet', 'Tea'],
 ['Powder', 'Cheese', ''],
 ['Bread', 'Ghee', 'Yougurt', 'Milk', 'Coffee'],
 ['Powder', ''],
 ['Coffee'],
 ['Powder', 'Butter', 'Lassi', 'Ghee', ''],
 ['Lassi', 'Bread', 'Coffee'],
 ['Powder', 'Milk', 'Sugar', ''],
 ['Ghee', 'Milk', 'Coffee'],
 ['Powder', 'Yougurt', 'Sweet', ''],
 ['Coffee'],
 ['Powder', 'Tea'],
 ['Powder', 'Panner', 'Sweet', 'Ghee', 'Milk', 'Sugar', ''],
 ['Lassi', 'Bread', 'Panner', 'Tea'],
 ['Powder', 'Milk', ''],
 ['Ghee', 'Butter', 'Tea'],
 ['Powder', 'Bread', 'Sweet', 'Sugar', 'Yougurt', ''],
 ['Tea'],
 ['Powder', 'Panner', 'Coffee'],
 ['Powder', ''],
 ['Milk', 'Butter', 'Tea'],
 ['Powder', 'Sugar', 'Sweet', ''],
 ['Coffee'],
 ['Powder', 'Milk', 'Yougurt', 'Cheese', 'Tea'],
 ['Powder', 'Sugar', 'Bread', ''],
 ['Coffee'],
 ['Powder', 'Lassi', 'Panner', 'Bread', 'Butter', 'Tea'],
 ['Powder', ''],
 ['Cheese', 'Bread', 'Sugar', 'Sweet', 'Milk', 'Coffee'],
 ['Powder', ''],
 ['Butter', 'Ghee', 'Sugar', ''],
 ['Sugar', 'Yougurt', 'Coffee'],
 ['Powder', 'Butter', 'Sweet', ''],
 ['Panner', 'Ghee', ''],
 ['Sweet', 'Lassi', 'Ghee', 'Coffee'],
 ['Powder', 'Sugar', 'Butter', ''],
 ['Tea'],
 ['Powder', 'Butter', 'Sugar', ''],
 ['Tea'],
 ['Powder', 'Coffee'],
 ['Powder', 'Cheese', 'Milk', 'Lassi', ''],
 ['Panner', 'Lassi', 'Butter', 'Coffee'],
 ['Powder', ''],
 ['Butter', 'Sugar', 'Lassi', 'Panner', ''],
 ['Milk', 'Cheese', 'Panner', 'Coffee'],
 ['Powder', 'Sweet', ''],
 ['Panner', 'Tea'],
 ['Powder', 'Lassi', 'Yougurt', 'Coffee'],
 ['Powder', 'Bread', 'Cheese', 'Ghee', ''],
 ['Butter', 'Panner', 'Coffee'],
 ['Powder', 'Sweet', 'Lassi', ''],
 ['Lassi', 'Cheese', 'Panner', 'Bread', 'Ghee', 'Milk', 'Sweet', 'Sugar', ''],
 ['Ghee', 'Yougurt', 'Coffee'],
 ['Powder', 'Panner', ''],
 ['Coffee'],
 ['Powder', 'Yougurt', 'Ghee', 'Cheese', 'Bread', ''],
 ['Lassi', 'Tea'],
 ['Powder', 'Panner', 'Butter', 'Sweet', ''],
 ['Milk', 'Sweet', 'Butter', 'Cheese', 'Tea'],
 ['Powder', 'Panner', ''],
 ['Tea'],
 ['Powder', 'Lassi', 'Coffee'],
 ['Powder', 'Cheese', 'Butter', 'Sugar', 'Sweet', 'Milk', ''],
 ['Sweet', 'Bread', 'Coffee'],
 ['Powder', 'Cheese', 'Yougurt', 'Ghee', 'Tea'],
 ['Powder', 'Milk', ''],
 ['Yougurt', 'Milk', 'Bread', 'Butter', 'Lassi', 'Cheese', 'Sweet', ''],
 ['Yougurt', 'Milk', 'Butter', ''],
 ['Tea'],
 ['Powder', 'Bread', 'Sweet', 'Cheese', ''],
 ['Panner', 'Tea'],
 ['Powder', ''],
 ['Bread', 'Panner', 'Cheese', 'Butter', 'Yougurt', ''],
 ['Coffee'],
 ['Powder', 'Tea'],
 ['Powder', 'Sweet', 'Bread', 'Milk', 'Lassi', 'Ghee', ''],
 ['Yougurt', 'Lassi', 'Cheese', 'Sugar', 'Butter', ''],
 ['Milk', 'Yougurt', 'Tea'],
 ['Powder', 'Lassi', 'Sweet', 'Cheese', 'Bread', ''],
 ['Milk', 'Coffee'],
 ['Powder', 'Cheese', 'Panner', 'Ghee', 'Sugar', 'Tea'],
 ['Powder', 'Sweet', ''],
 ['Sugar', 'Butter', 'Tea'],
 ['Powder', 'Coffee'],
 ['Powder', 'Bread', 'Milk', 'Lassi', ''],
 ['Ghee', 'Tea'],
 ['Powder', 'Sweet', ''],
 ['Lassi', 'Panner', 'Milk', 'Tea'],
 ['Powder', 'Ghee', ''],
 ['Milk', 'Panner', 'Sweet', 'Sugar', 'Bread', 'Butter', ''],
 ['Sugar', 'Milk', 'Bread', ''],
 ['Butter', 'Milk', 'Tea'],
 ['Powder', 'Yougurt', 'Ghee', ''],
 ['Butter', 'Bread', 'Cheese', 'Coffee'],
 ['Powder', ''],
 ['Cheese', 'Ghee', 'Coffee'],
 ['Powder', 'Yougurt', 'Bread', 'Tea'],
 ['Powder', 'Butter', ''],
 ['Yougurt', 'Coffee'],
 ['Powder', 'Sugar', 'Milk', ''],
 ['Ghee', 'Bread', 'Tea'],
 ['Powder', 'Butter', 'Panner', 'Cheese', ''],
 ['Bread',
  'Butter',
  'Milk',
  'Panner',
  'Sugar',
  'Cheese',
  'Sweet',
  'Ghee',
  'Yougurt',
  ''],
 ['Butter', 'Panner', 'Milk', ''],
 ['Tea'],
 ['Powder', 'Panner', 'Butter', 'Sugar', ''],
 ['Panner', 'Sweet', 'Cheese', 'Lassi', 'Sugar', 'Coffee'],
 ['Powder', ''],
 ['Butter', 'Cheese', 'Lassi', 'Yougurt', 'Ghee', ''],
 ['Milk', 'Sugar', 'Cheese', 'Sweet', 'Panner', ''],
 ['Sugar', 'Cheese', 'Butter', 'Ghee', 'Coffee'],
 ['Powder', 'Panner', ''],
 ['Ghee', 'Milk', 'Sweet', ''],
 ['Yougurt', 'Lassi', 'Sweet', 'Milk', 'Ghee', 'Coffee'],
 ['Powder', 'Bread', 'Butter', ''],
 ['Sugar', 'Cheese', 'Tea'],
 ['Powder', 'Milk', 'Ghee', 'Bread', 'Panner', ''],
 ['Sugar', 'Lassi', 'Cheese', 'Butter', ''],
 ['Bread', 'Cheese', 'Yougurt', 'Coffee'],
 ['Powder', 'Sugar', 'Butter', ''],
 ['Coffee'],
 ['Powder', 'Sugar', 'Lassi', 'Tea'],
 ['Powder', 'Ghee', 'Cheese', ''],
 ['Tea'],
 ['Powder', 'Sugar', 'Sweet', 'Yougurt', 'Coffee'],
 ['Powder', 'Ghee', 'Cheese', 'Panner', ''],
 ['Butter', 'Milk', 'Ghee', 'Yougurt', 'Coffee'],
 ['Powder', 'Sweet', 'Bread', 'Sugar', ''],
 ['Lassi', 'Tea'],
 ['Powder', 'Sugar', 'Yougurt', ''],
 ['Bread', 'Sugar', 'Coffee'],
 ['Powder', 'Tea'],
 ['Powder', 'Lassi', 'Cheese', 'Yougurt', ''],
 ['Butter', 'Milk', 'Coffee'],
 ['Powder', 'Sugar', 'Ghee', 'Panner', 'Tea'],
 ['Powder', ''],
 ['Sweet', 'Yougurt', 'Bread', 'Tea'],
 ['Powder', 'Coffee'],
 ['Powder', 'Cheese', ''],
 ['Butter', 'Cheese', 'Coffee'],
 ['Powder', 'Bread', 'Tea'],
 ['Powder', ''],
 ['Milk', 'Butter', 'Lassi', ''],
 ['Milk', 'Lassi', 'Panner', 'Butter', 'Bread', 'Coffee'],
 ['Powder', 'Ghee', 'Sugar', ''],
 ['Coffee'],
 ['Powder', 'Butter', 'Bread', 'Lassi', 'Sugar', 'Panner', 'Yougurt', ''],
 ['Yougurt', 'Panner', 'Butter', 'Coffee'],
 ['Powder', 'Tea'],
 ['Powder', 'Bread', 'Milk', ''],
 ['Coffee'],
 ['Powder', 'Panner', 'Milk', ''],
 ['Lassi', 'Coffee'],
 ['Powder', 'Tea'],
 ['Powder', ''],
 ['Cheese', 'Tea'],
 ['Powder', 'Yougurt', 'Ghee', ''],
 ['Cheese', 'Lassi', 'Panner', 'Tea'],
 ['Powder', 'Sugar', 'Butter', 'Bread', 'Milk', 'Ghee', 'Sweet', ''],
 ['Milk', 'Coffee'],
 ['Powder', 'Butter', 'Ghee', 'Lassi', 'Tea'],
 ['Powder', ''],
 ['Tea'],
 ['Powder',
  'Butter',
  'Milk',
  'Sugar',
  'Panner',
  'Lassi',
  'Sweet',
  'Cheese',
  'Ghee',
  ''],
 ['Yougurt', 'Coffee'],
 ['Powder', 'Tea'],
 ['Powder', 'Sugar', 'Panner', ''],
 ['Yougurt', 'Bread', 'Sugar', 'Lassi', 'Coffee'],
 ['Powder', 'Panner', 'Ghee', 'Cheese', ''],
 ['Sugar', 'Tea'],
 ['Powder', 'Butter', 'Coffee'],
 ['Powder', 'Yougurt', ''],
 ['Ghee', 'Butter', 'Bread', 'Cheese', 'Lassi', ''],
 ['Cheese', 'Panner', 'Sweet', 'Yougurt', 'Lassi', 'Milk', 'Ghee', 'Tea'],
 ['Powder', 'Butter', ''],
 ['Ghee', 'Milk', ''],
 ['Sugar', 'Panner', 'Milk', 'Bread', 'Coffee'],
 ['Powder', 'Tea'],
 ['Powder', 'Ghee', ''],
 ['Tea'],
 ['Powder', 'Sweet', 'Butter', ''],
 ['Coffee'],
 ['Powder', 'Butter', ''],
 ['Tea'],
 ['Powder', 'Bread', 'Sweet', 'Milk', 'Sugar', 'Panner', 'Yougurt', ''],
 ['Lassi', 'Panner', 'Butter', 'Milk', 'Cheese', 'Coffee'],
 ['Powder', 'Tea'],
 ['Powder', ''],
 ['Tea'],
 ['Powder', 'Milk', ''],
 ['Yougurt', 'Tea'],
 ['Powder', 'Sugar', 'Milk', 'Coffee'],
 ['Powder', 'Sweet', 'Panner', 'Bread', ''],
 ['Butter', 'Sugar', ''],
 ['Tea'],
 ['Powder', 'Sweet', 'Bread', 'Butter', 'Yougurt', ''],
 ['Yougurt', 'Sugar', 'Bread', ''],
 ['Panner', 'Ghee', 'Cheese', ''],
 ['Bread', 'Milk', 'Coffee'],
 ['Powder', ''],
 ['Ghee', 'Tea'],
 ['Powder', ''],
 ['Milk', 'Butter', ''],
 ['Lassi', 'Milk', 'Sweet', 'Sugar', 'Butter', 'Coffee'],
 ['Powder', 'Ghee', ''],
 ['Butter', 'Ghee', 'Sugar', 'Cheese', 'Panner', 'Tea'],
 ['Powder', 'Yougurt', ''],
 ['Coffee'],
 ['Powder', 'Lassi', 'Ghee', ''],
 ['Sugar', 'Milk', 'Sweet', 'Tea'],
 ['Powder', 'Bread', 'Coffee'],
 ['Powder', 'Panner', ''],
 ['Yougurt', 'Bread', 'Tea'],
 ['Powder', 'Lassi', ''],
 ['Ghee', 'Tea'],
 ['Powder', 'Panner', 'Milk', 'Bread', ''],
 ['Milk', 'Butter', ''],
 ['Ghee', 'Tea'],
 ['Powder', 'Coffee'],
 ['Powder', 'Sugar', ''],
 ['Ghee', 'Cheese', 'Lassi', 'Butter', 'Sweet', 'Milk', 'Tea'],
 ['Powder', 'Yougurt', ''],
 ['Yougurt', 'Cheese', 'Butter', 'Sweet', 'Coffee'],
 ['Powder', 'Milk', 'Ghee', ''],
 ['Milk', 'Sweet', 'Ghee', ''],
 ['Panner', 'Lassi', 'Coffee'],
 ['Powder', 'Yougurt', 'Butter', 'Sugar', 'Milk', 'Sweet', ''],
 ['Coffee'],
 ['Powder', 'Ghee', 'Lassi', 'Butter', 'Cheese', 'Yougurt', ''],
 ['Cheese', 'Lassi', 'Butter', 'Yougurt', ''],
 ['Sweet', 'Butter', 'Tea'],
 ['Powder', 'Yougurt', 'Ghee', ''],
 ['Lassi', 'Bread', 'Sugar', 'Milk', 'Tea'],
 ['Powder', ''],
 ['Milk', 'Butter', 'Yougurt', 'Sugar', 'Lassi', 'Bread', ''],
 ['Tea'],
 ['Powder', 'Coffee'],
 ['Powder', 'Milk', 'Lassi', 'Butter', 'Ghee', ''],
 ['Ghee', 'Butter', 'Sweet', 'Tea'],
 ['Powder', 'Sugar', ''],
 ['Coffee'],
 ['Powder', 'Ghee', 'Cheese', ''],
 ['Sweet', 'Ghee', 'Butter', 'Coffee'],
 ['Powder', 'Lassi', ''],
 ['Sugar', 'Bread', 'Butter', 'Cheese', 'Milk', 'Panner', 'Yougurt', ''],
 ['Butter', 'Sweet', 'Cheese', 'Yougurt', 'Milk', 'Sugar', 'Coffee'],
 ['Powder', ''],
 ['Sugar', 'Panner', 'Yougurt', ''],
 ['Bread', 'Sweet', ''],
 ['Sweet', 'Butter', 'Lassi', 'Yougurt', 'Milk', 'Sugar', 'Coffee'],
 ['Powder', 'Cheese', 'Tea'],
 ['Powder', ''],
 ['Yougurt', 'Coffee'],
 ['Powder', 'Lassi', 'Cheese', 'Sugar', ''],
 ['Tea'],
 ['Powder',
  'Panner',
  'Bread',
  'Yougurt',
  'Ghee',
  'Sugar',
  'Milk',
  'Cheese',
  'Butter',
  ''],
 ['Ghee', 'Lassi', 'Bread', 'Panner', 'Yougurt', 'Sugar', ''],
 ['Sugar', 'Lassi', 'Tea'],
 ['Powder', 'Ghee', ''],
 ['Yougurt', 'Cheese', 'Bread', 'Coffee'],
 ['Powder', 'Sugar', 'Tea'],
 ['Powder', 'Panner', ''],
 ['Sugar', 'Coffee'],
 ['Powder', 'Cheese', ''],
 ['Yougurt', 'Cheese', 'Panner', 'Coffee'],
 ['Powder', 'Milk', ''],
 ['Sweet', 'Coffee'],
 ['Powder', 'Tea'],
 ['Powder', 'Lassi', 'Cheese', ''],
 ['Lassi', 'Cheese', 'Sugar', 'Tea'],
 ['Powder', ''],
 ['Bread', 'Coffee'],
 ['Powder', 'Milk', 'Lassi', 'Yougurt', 'Butter', 'Cheese', ''],
 ['Milk', 'Cheese', 'Sugar', ''],
 ['Tea'],
 ['Powder', 'Sweet', 'Bread', 'Lassi', 'Coffee'],
 ['Powder', 'Panner', 'Milk', ''],
 ['Yougurt', 'Tea'],
 ['Powder', ''],
 ['Cheese', 'Butter', 'Coffee'],
 ['Powder', 'Yougurt', 'Bread', 'Sweet', 'Lassi', ''],
 ['Tea'],
 ['Powder', 'Panner', 'Ghee', 'Sugar', ''],
 ['Cheese', 'Sweet', 'Coffee'],
 ['Powder', 'Ghee', 'Panner', ''],
 ['Panner', 'Coffee'],
 ['Powder', 'Milk', 'Cheese', 'Ghee', ''],
 ['Sweet', 'Tea'],
 ['Powder', 'Lassi', 'Sugar', 'Ghee', 'Cheese', 'Bread', 'Coffee'],
 ['Powder', ''],
 ['Milk', 'Sugar', 'Yougurt', 'Tea'],
 ['Powder', 'Cheese', 'Coffee'],
 ['Powder', ''],
 ['Lassi', 'Panner', ''],
 ['Panner', 'Sugar', 'Sweet', 'Cheese', 'Lassi', ''],
 ['Tea'],
 ['Powder', 'Cheese', 'Coffee'],
 ['Powder', 'Bread', 'Milk', 'Butter', 'Lassi', 'Panner', 'Yougurt', ''],
 ['Cheese', 'Panner', 'Sugar', ''],
 ['Yougurt', 'Coffee'],
 ['Powder', 'Sugar', ''],
 ['Tea'],
 ['Powder', 'Bread', 'Yougurt', 'Panner', 'Coffee'],
 ['Powder', ''],
 ['Sugar', 'Sweet', 'Cheese', 'Milk', 'Coffee'],
 ['Powder', 'Ghee', ''],
 ['Sweet', 'Bread', 'Lassi', 'Butter', 'Milk', 'Panner', 'Tea'],
 ['Powder', 'Yougurt', ''],
 ['Cheese', 'Sweet', 'Tea'],
 ['Powder', 'Coffee'],
 ['Powder', 'Yougurt', 'Butter', 'Ghee', ''],
 ['Panner', 'Milk', 'Cheese', 'Yougurt', 'Sweet', 'Ghee', 'Butter', ''],
 ['Sugar', 'Lassi', 'Cheese', 'Milk', 'Sweet', 'Bread', 'Coffee'],
 ['Powder', ''],
 ['Lassi', 'Milk', 'Ghee', 'Tea'],
 ['Powder', ''],
 ['Yougurt', 'Ghee', 'Panner', 'Sweet', 'Milk', 'Coffee'],
 ['Powder', ''],
 ['Butter', 'Bread', 'Yougurt', 'Sugar', 'Milk', ''],
 ['Cheese', 'Bread', ''],
 ['Sweet', 'Yougurt', ''],
 ['Ghee', 'Coffee'],
 ['Powder', 'Bread', 'Lassi', 'Milk', 'Yougurt', ''],
 ['Sweet',
  'Yougurt',
  'Milk',
  'Bread',
  'Butter',
  'Sugar',
  'Ghee',
  'Panner',
  ''],
 ['Sweet', 'Sugar', 'Ghee', 'Coffee'],
 ['Powder', 'Milk', 'Cheese', ''],
 ['Tea'],
 ['Powder', 'Bread', ''],
 ['Coffee'],
 ['Powder', 'Milk', 'Yougurt', 'Ghee', 'Sugar', 'Sweet', ''],
 ['Panner', 'Sweet', 'Butter', 'Lassi', 'Cheese', 'Yougurt', ''],
 ['Milk', 'Coffee'],
 ['Powder', 'Ghee', 'Butter', 'Yougurt', ''],
 ['Tea'],
 ['Powder', 'Milk', ''],
 ['Cheese', 'Ghee', 'Sweet', ''],
 ['Sweet', 'Panner', 'Milk', 'Butter', 'Tea'],
 ['Powder', 'Lassi', 'Ghee', ''],
 ['Sugar', 'Cheese', 'Tea'],
 ['Powder', ''],
 ['Sugar', 'Coffee'],
 ['Powder', 'Cheese', 'Yougurt', ''],
 ['Bread', 'Cheese', 'Sugar', 'Panner', ''],
 ['Ghee', 'Bread', 'Coffee'],
 ['Powder', 'Tea'],
 ['Powder', 'Lassi', ''],
 ['Yougurt', 'Panner', 'Coffee'],
 ['Powder', 'Sugar', 'Tea'],
 ['Powder', 'Milk', ''],
 ['Cheese', 'Coffee'],
 ['Powder', 'Panner', ''],
 ['Sugar', 'Cheese', 'Tea'],
 ['Powder', 'Ghee', 'Milk', 'Panner', 'Yougurt', ''],
 ['Ghee', 'Bread', 'Milk', 'Butter', 'Coffee'],
 ['Powder', 'Yougurt', 'Lassi', ''],
 ['Lassi', 'Milk', 'Cheese', ''],
 ['Butter', 'Ghee', 'Bread', 'Lassi', 'Sugar', 'Panner', ''],
 ['Tea'],
 ['Powder', 'Bread', 'Coffee'],
 ['Powder', 'Ghee', ''],
 ['Ghee', 'Cheese', 'Bread', 'Sweet', ''],
 ['Panner', 'Ghee', 'Yougurt', 'Sweet', 'Sugar', 'Cheese', 'Lassi', ''],
 ['Tea'],
 ['Powder', 'Cheese', 'Coffee'],
 ['Powder', 'Lassi', 'Yougurt', ''],
 ['Ghee', 'Lassi', 'Sugar', 'Yougurt', ''],
 ['Ghee', 'Sweet', 'Butter', 'Milk', 'Sugar', 'Lassi', ''],
 ['Ghee', 'Tea'],
 ['Powder', 'Sweet', 'Bread', 'Panner', ''],
 ['Bread', 'Yougurt', 'Ghee', 'Milk', 'Coffee'],
 ['Powder', 'Panner', ''],
 ['Sweet', 'Tea'],
 ['Powder', 'Yougurt', 'Cheese', 'Bread', 'Ghee', 'Sugar', 'Butter', ''],
 ['Bread', 'Coffee'],
 ['Powder', 'Sweet', 'Panner', 'Sugar', ''],
 ['Ghee', 'Sugar', 'Butter', 'Milk', 'Panner', 'Bread', 'Sweet', ''],
 ['Cheese', 'Yougurt', 'Milk', 'Tea'],
 ['Powder', ''],
 ['Milk', 'Coffee'],
 ['Powder', ''],
 ['Bread', 'Tea'],
 ['Powder', 'Milk', 'Ghee', ''],
 ['Tea'],
 ['Powder', 'Cheese', 'Milk', 'Lassi', 'Sweet', 'Bread', ''],
 ['Yougurt', 'Coffee'],
 ['Powder', 'Sugar', 'Bread', 'Lassi', 'Cheese', ''],
 ['Sweet', 'Milk', 'Tea'],
 ['Powder', 'Lassi', 'Panner', 'Sugar', 'Coffee'],
 ['Powder', 'Butter', ''],
 ['Cheese', 'Butter', 'Bread', 'Sweet', ''],
 ['Yougurt', 'Sugar', 'Ghee', 'Tea'],
 ['Powder', 'Butter', 'Coffee'],
 ['Powder', 'Milk', ''],
 ['Yougurt', 'Lassi', 'Butter', 'Cheese', 'Coffee'],
 ['Powder', 'Ghee', 'Tea'],
 ['Powder', 'Sugar', ''],
 ['Bread', 'Sugar', ''],
 ['Sweet', 'Coffee'],
 ['Powder', 'Tea'],
 ['Powder', 'Ghee', 'Milk', ''],
 ['Butter', 'Bread', 'Ghee', 'Cheese', 'Tea'],
 ['Powder', 'Milk', 'Sweet', ''],
 ['Panner', 'Lassi', 'Coffee'],
 ['Powder', 'Tea'],
 ['Powder', 'Bread', ''],
 ['Panner', 'Butter', 'Yougurt', 'Cheese', 'Bread', 'Sugar', ''],
 ['Cheese', 'Coffee'],
 ['Powder', 'Ghee', 'Yougurt', 'Bread', 'Tea'],
 ['Powder', 'Lassi', 'Butter', ''],
 ['Panner', 'Bread', 'Coffee'],
 ['Powder', 'Cheese', 'Ghee', 'Sweet', 'Milk', ''],
 ['Sweet', 'Bread', 'Cheese', 'Yougurt', 'Butter', ''],
 ['Cheese', 'Ghee', 'Yougurt', 'Lassi', 'Sweet', ''],
 ['Coffee'],
 ['Powder', 'Lassi', 'Bread', 'Cheese', 'Sweet', 'Milk', 'Panner', ''],
 ['Sugar', 'Milk', 'Yougurt', 'Ghee', ''],
 ['Panner', 'Sugar', 'Yougurt', 'Milk', 'Coffee'],
 ['Powder', 'Butter', 'Lassi', ''],
 ['Lassi', 'Bread', 'Ghee', 'Yougurt', 'Milk', ''],
 ['Bread', 'Sweet', 'Ghee', ''],
 ['Bread', 'Ghee', 'Sugar', 'Butter', 'Lassi', ''],
 ['Panner', 'Ghee', 'Coffee'],
 ['Powder', ''],
 ['Lassi', 'Yougurt', 'Butter', 'Bread', 'Cheese', 'Sugar', ''],
 ['Ghee', 'Yougurt', 'Milk', 'Sweet', 'Bread', 'Sugar', 'Coffee'],
 ['Powder', ''],
 ['Milk', 'Sweet', 'Lassi', 'Ghee', ''],
 ['Milk', 'Coffee'],
 ['Powder', 'Ghee', 'Sugar', 'Yougurt', ''],
 ['Yougurt', 'Lassi', 'Butter', 'Sugar', 'Bread', ''],
 ['Yougurt', 'Sweet', 'Tea'],
 ['Powder', ''],
 ['Coffee'],
 ['Powder', 'Bread', 'Sugar', 'Lassi', 'Tea'],
 ['Powder', 'Ghee', 'Sweet', 'Milk', ''],
 ['Cheese', 'Tea'],
 ['Powder', 'Coffee'],
 ['Powder', 'Sugar', 'Milk', 'Sweet', 'Ghee', 'Butter', ''],
 ['Panner', 'Yougurt', 'Cheese', 'Milk', 'Lassi', 'Tea'],
 ['Powder', ''],
 ['Bread', 'Sugar', 'Ghee', ''],
 ['Ghee', 'Lassi', 'Coffee'],
 ['Powder', 'Panner', 'Milk', 'Sweet', ''],
 ['Coffee'],
 ['Powder', 'Panner', 'Tea'],
 ['Powder', 'Yougurt', 'Bread', 'Lassi', ''],
 ['Yougurt', 'Milk', 'Tea'],
 ['Powder', 'Sugar', 'Coffee'],
 ['Powder', 'Sweet', ''],
 ['Sweet', 'Panner', 'Ghee', 'Butter', 'Sugar', 'Tea'],
 ['Powder', 'Milk', 'Coffee'],
 ['Powder', ''],
 ['Ghee', 'Coffee'],
 ['Powder', 'Cheese', 'Panner', 'Yougurt', 'Tea'],
 ['Powder', ''],

In [80]:
te = TransactionEncoder()
te_fd = te.fit(food_item).transform(food_item)
df = pd.DataFrame(te_fd, columns=te.columns_)
df

,,Bread,Butter,Cheese,Coffee,Ghee,Lassi,Milk,Panner,Powder,Sugar,Sweet,Tea,Yougurt
0,False,False,False,False,True,False,True,False,False,False,False,False,False,False
1,True,False,True,True,False,True,False,False,False,True,False,False,False,True
2,False,False,False,False,True,True,False,False,False,False,False,False,False,False
3,True,False,False,False,False,False,False,False,False,True,False,False,False,False
4,False,False,False,False,False,False,True,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23413,False,True,False,False,True,False,False,False,False,False,True,False,False,False
23414,True,False,False,True,False,False,False,False,False,True,False,False,False,False
23415,True,True,False,True,False,False,False,True,False,False,False,False,False,True
23416,True,True,False,True,False,True,False,False,False,False,True,False,False,True
23417,True,True,False,False,False,False,False,False,True,False,False,False,False,True

In [82]:
df = df.iloc[:,1:]  # to remove "" column at pos 0
df

,Bread,Butter,Cheese,Coffee,Ghee,Lassi,Milk,Panner,Powder,Sugar,Sweet,Tea,Yougurt
0,False,False,False,True,False,True,False,False,False,False,False,False,False
1,False,True,True,False,True,False,False,False,True,False,False,False,True
2,False,False,False,True,True,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,True,False,False,False,False
4,False,False,False,False,False,True,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
23413,True,False,False,True,False,False,False,False,False,True,False,False,False
23414,False,False,True,False,False,False,False,False,True,False,False,False,False
23415,True,False,True,False,False,False,True,False,False,False,False,False,True
23416,True,False,True,False,True,False,False,False,False,True,False,False,True
23417,True,False,False,False,False,False,False,True,False,False,False,False,True

In [83]:
def gen_rules(min_support,min_confidence):
    itemsets = apriori(df,min_support=min_support,use_colnames=True)
    rules = association_rules(itemsets,metric='confidence',min_threshold=min_confidence)
    rules = rules[['antecedents','consequents','support','confidence','lift']]
    relv_rules = rules[rules['lift']>1]
    return relv_rules.sort_values(by=['confidence','lift','support'],ascending=False)

In [84]:
interact(gen_rules,
         min_support = widgets.FloatSlider(value=0.01,min=0.01,max=0.1,step=0.01,description='Min Support:'),
         min_confidence = widgets.FloatSlider(value=0.01,min=0,max=1,step=0.01,description='Min Confidence:'))

interactive(children=(FloatSlider(value=0.01, description='Min Support:', max=0.1, min=0.01, step=0.01), Float…